### PR TITLE
MVP to fix gem metadata command

### LINKED ISSUE #4710: chef_gem and gem metadata don't play well
## Description

If one has a gem section in metadata and a chef_gem resource, the resource implodes. `chef_gem` needs to bundle bust.

## Chef Version

12.8.x

## Client Output

https://gist.github.com/thommay/1151fc72d256edd57c5e

### PR DESCRIPTION
**Pull request by lamont-granquist**
The gem command in the cookbook metadata uses the bundler API but needs to not leave the chef-client in a 'bundled' state.

Trying to do this in-process always results in a bundled state.  The result is that /other/ cookbooks that access other gems such as a cookbook with:

```ruby
chef_gem "mysql"
require "mysql"
```

Will fail.  Since we can't convert every cookbook from using chef_gem to get metadata (for backcompat reasons, practicality reasons, and because of native gems and build-essentials deps) we need a workaround.

Best workaround I can come up with is to simply fork off a process.  Since windows does not support fork, the easiest way to implement this is to shell_out to `bundle install`.  When the bundle install returns, we are guaranteed that the spawned process hasn't twiddled at all with our own internal state.

This, however, breaks the ability to get `requires` lines in the gem metadata to work since those would only execute in the subprocess and are flushed with the rest of the state.

closes #4710

### CODE REVIEW

**Comment by lamont-granquist** [comment]
this'll break 'requires' in the gem metadata itself.

File: lib/chef/cookbook/gem_installer.rb [hunk 1]
```diff
@@ -45,10 +46,16 @@ def install
...
-                gem(*args)
+            Dir.mktmpdir("chef-gem-bundle") do |dir|
+              File.open("#{dir}/Gemfile", "w+") do |tf|
+                tf.puts "source '#{Chef::Config[:rubygems_url]}'"
+                cookbook_gems.each do |args|
+                  tf.puts "gem #{args.map { |i| "'#{i}'" }.join(' ')}"
+                end
+                tf.close
+                Dir.chdir(dir) do
+                  so = shell_out!("bundle install")
```
Comment (coderanger) [inline lib/chef/cookbook/gem_installer.rb]: Do we want to make sure to specify Chef's bundler binary somehow?

File: lib/chef/cookbook/gem_installer.rb [hunk 2]
```diff
@@ -45,10 +46,16 @@ def install
...
           begin
-            inline_gemfile do
-              source Chef::Config[:rubygems_url]
-              cookbook_gems.each do |args|
-                gem(*args)
+            Dir.mktmpdir("chef-gem-bundle") do |dir|
+              File.open("#{dir}/Gemfile", "w+") do |tf|
+                tf.puts "source '#{Chef::Config[:rubygems_url]}'"
+                cookbook_gems.each do |args|
+                  tf.puts "gem #{args.map { |i| "'#{i}'" }.join(' ')}"
```
Comment (coderanger) [inline lib/chef/cookbook/gem_installer.rb]: Are we planning support stuff like `git` sources? I think that would have worked with the prior code but not this.

File: lib/chef/cookbook/gem_installer.rb [hunk 3]
```diff
@@ -45,10 +46,16 @@ def install
...
+                end
+                tf.close
+                Dir.chdir(dir) do
```
Comment (coderanger) [inline lib/chef/cookbook/gem_installer.rb]: For the hell of it, you can use `cwd: dir` on the shell out :)

File: lib/chef/cookbook/gem_installer.rb (hunk 2 above)
Comment (lamont-granquist) [inline lib/chef/cookbook/gem_installer.rb]: Yeah, I'm just drawing a blank today on how to render those cases...

File: lib/chef/cookbook/gem_installer.rb (hunk 1 above)
Comment (lamont-granquist) [inline lib/chef/cookbook/gem_installer.rb]: I think we probably do?  Maybe via the omnibus-detection stuff inside the rubygems provider that we use for chef_gem and then run bundler from that path...

File: lib/chef/cookbook/gem_installer.rb (hunk 2 above)
Comment (coderanger) [inline lib/chef/cookbook/gem_installer.rb]: Change it to `"gem(*#{args.inspect})"`?

File: lib/chef/cookbook/gem_installer.rb (hunk 1 above)
Comment (coderanger) [inline lib/chef/cookbook/gem_installer.rb]: That sounds right. We can rely on the appbundle stub on `chef-client` itself to bust rvm envvars I think. I'm sure there is some way this can still be broken but ¯\_(ツ)_/¯

**Comment by coderanger** [comment]
:+1: This is unfortunate but I think this is better than what we have now given the constraints.

**Comment by coderanger** [comment]
One thing I might add is some debugging output stuffs. Like echo the generated gemfile to debug log :)

**Comment by lamont-granquist** [comment]
Yeah this gets us from "totally broken feature" to "usable with issues" and is probably the best I can come up with before the 12.9.x release next week.

Gemfile to the debug log is probably a good idea..
