### PR TITLE
Fix snap_package bugs

### LINKED ISSUE #9041: service provider doesn't handle `indirect` systemd units
# Description
If a unit is "indirect":

```
● systemd-journal-remote.service - Journal Remote Sink Service
   Loaded: loaded (/lib/systemd/system/systemd-journal-remote.service; indirect; vendor preset: disabled)
```

Then `service`, when set to `:disable` it will always try to disable it, ever time. However, `systemd_unit` does not make this mistake.

## Chef Version
14.13.11

## Platform Version
Ubuntu 18

## Replication Case
On a typical Ubuntu18 box set:

```
service 'systemd-journal-remote' do
  action [:stop, :disable]
end
```

And it will re-disable it every run. But the same thing with `systemd_unit` does not.

### PR DESCRIPTION
**Pull request by jaymzh**
First and foremost this fixes the bug in which #8827 where
`snap_package` hangs forever.

See the comment in the code for the nitty-gritty details, but snap never
returns an EOF so you have to jump through GREAT hoops not to hang
forever.

UNLESS you want to use nonblock+read, but it takes MUCH longer:

```
[phil@ldt-hardwired ~]$ time /tmp/test.rb char

real    0m0.252s
user    0m0.207s
sys     0m0.044s
[phil@ldt-hardwired ~]$ time /tmp/test.rb select

real    0m5.244s
user    0m0.183s
sys     0m0.056s
```

That's just for doing `GET /v2/snaps/black`

Second, if you try to install a snap that doesn't exist on the `stable`
channel then Chef crashes with a `undefined method [] on nil`, so let's
check for that explicitly.

And a bunch of other fixes that were required to even install anything:

* prevent get_current_versions from returning `[nil]`
* don't try to 'update' when something is not yet installed
* don't try to install versions, install packages
* don't try to push ruby hashes into HTTP without JSONing them first
* when installing, install one at a time, it's the only API that accepts a channel
* options is an array, not a hash

NOTE... there's a lot of janky here. A lot. It's the minimalist stuff
from #9106 I could pull in, while also making the socket stuff not
painfully slow. That PR aims to support versions and lots of other and
should be fixed up and [eventually] merged... but in the meantime this
provider doesn't even come close to working and this at least gets
packages installing.

After this, I never want to touch snap again.

Aha! Link: https://chef.aha.io/features/SH-114

### CODE REVIEW

File: lib/chef/provider/package/snap.rb [hunk 1]
```diff
@@ -311,6 +349,9 @@ def get_latest_package_version(name, channel)
             raise Chef::Exceptions::Package, json["result"], caller
           end
 
+          unless json["result"][0]["channels"]["latest/#{channel}"]
+            fail "No version of #{name} in channel #{channel}"
```
Comment (phiggins) [inline lib/chef/provider/package/snap.rb:353]: Since `fail` is a synonym of `raise`, should this use a more specific exception class like the `raise` a few lines up?

File: lib/chef/provider/package/snap.rb [hunk 2]
```diff
@@ -138,10 +138,48 @@ def call_snap_api(method, uri, post_data = nil?)
...
+                begin
+                  result = JSON.parse(body)
+                  # if we get here, we were able to parse the json so we
+                  # are done reading
+                  break
+                rescue JSON::ParserError
+                  next
+                end
+              end
+              result
```
Comment (phiggins) [inline lib/chef/provider/package/snap.rb:182]: If `read_nonblock` and friends don't work or are undesirable here, since a valid json document will end with a `]` or a `}` (right?), this could read until one of those characters is found before attempting to parse json.

File: lib/chef/provider/package/snap.rb (hunk 1 above)
Comment (jaymzh) [reply lib/chef/provider/package/snap.rb]: yes it should. Fixed.

File: lib/chef/provider/package/snap.rb (hunk 2 above)
Comment (jaymzh) [reply lib/chef/provider/package/snap.rb:198]: Nice optimization. Added.
Also note that in my new description I found you *can* make `read_nonblock` work, but it's 10x slower than this. ANd that was before your optimization.

File: lib/chef/provider/package/snap.rb [hunk 3]
```diff
@@ -59,30 +59,31 @@ def candidate_version
...
             installed_version(i)
-          end
+          end.compact
         end
 
         def install_package(names, versions)
           if new_resource.source
             install_snap_from_source(names, new_resource.source)
           else
-            resolved_names = names.each_with_index.map { |name, i| available_version(i).to_s unless name.nil? }
```
Comment (jaymzh) [inline lib/chef/provider/package/snap.rb:69]: this returns versions, not names.

File: lib/chef/provider/package/snap.rb [hunk 4]
```diff
@@ -59,30 +59,31 @@ def candidate_version
...
-            install_snaps(resolved_names)
+            install_snaps(names)
           end
         end
 
         def upgrade_package(names, versions)
           if new_resource.source
             install_snap_from_source(names, new_resource.source)
           else
-            resolved_names = names.each_with_index.map { |name, i| available_version(i).to_s unless name.nil? }
```
Comment (jaymzh) [inline lib/chef/provider/package/snap.rb:78]: same

File: lib/chef/provider/package/snap.rb [hunk 5]
```diff
@@ -59,30 +59,31 @@ def candidate_version
...
+            if get_current_versions.empty?
+              install_snaps(names, versions)
+            else
+              update_snaps(names)
+            end
           end
         end
 
         def remove_package(names, versions)
-          resolved_names = names.each_with_index.map { |name, i| installed_version(i).to_s unless name.nil? }
```
Comment (jaymzh) [inline lib/chef/provider/package/snap.rb:84]: same

File: lib/chef/provider/package/snap.rb [hunk 6]
```diff
@@ -129,19 +130,72 @@ def call_snap_api(method, uri, post_data = nil?)
             "Accept: application/json\r\n" +
             "Content-Type: application/json\r\n"
           if method == "POST"
-            request.concat("Content-Length: #{post_data.bytesize}\r\n\r\n#{post_data}")
```
Comment (jaymzh) [inline lib/chef/provider/package/snap.rb:132]: clearly no one ever tried this...

File: lib/chef/provider/package/snap.rb [hunk 7]
```diff
@@ -129,19 +130,72 @@ def call_snap_api(method, uri, post_data = nil?)
...
+              #
+              # So snapd doesn't return an EOF at the end of its body, so
+              # doing a normal read will just hang forever.
+              #
+              # Well, sort of. if, after it writes everything, you then send
+              # yet-another newline, it'll then send its EOF and promptly
+              # disconnect closing the pipe and preventing reading. so, you
+              # have to read first, and therein lies the EOF problem.
+              #
+              # So you can do non-blocking reads with selects, but it
```
Comment (jaymzh) [inline lib/chef/provider/package/snap.rb:158]: updated this with speed comment.

File: lib/chef/provider/package/snap.rb [hunk 8]
```diff
@@ -211,20 +265,22 @@ def install_snap_from_source(name, path)
...
+          snap_names.each do |snap|
+            response = post_snap(snap, "install", new_resource.channel, new_resource.options)
+            id = get_id_from_async_response(response)
+            wait_for_completion(id)
+          end
         end
 
         def update_snaps(snap_names)
-          response = post_snaps(snap_names, "refresh", new_resource.channel, new_resource.options)
+          response = post_snaps(snap_names, "refresh", nil, new_resource.options)
```
Comment (jaymzh) [inline lib/chef/provider/package/snap.rb:277]: afaict, updates generally happen within a channel, so I left this as batch, but that doesn't work with installs.

but when you do multiples you cannot specify a channel

File: lib/chef/provider/package/snap.rb [hunk 9]
```diff
@@ -278,18 +334,20 @@ def generate_snap_json(snap_names, action, channel, options, revision = nil)
...
           end
 
           # No defensive handling of params
           # Snap will throw the proper exception if called improperly
           # And we can provide that exception to the end user
-          request["classic"] = true if options["classic"]
-          request["devmode"] = true if options["devmode"]
-          request["jailmode"] = true if options["jailmode"]
+          if options
+            request["classic"] = true if options.include?("classic")
```
Comment (jaymzh) [inline lib/chef/provider/package/snap.rb:345]: lolz, not a hash.

**Comment by tas50** [comment]
Before we can merge this or #9106 we need to add some kitchen tests or snap_package exercising as many scenarios as we can reasonably do in a quick kitchen run. It's something we can't really test in unit tests and we need to have a reasonable level of confidence when merging future changes.

**Comment by jaymzh** [comment]
@tas50 - yup the few unittests that are there are basically useless. Yes, we should have a kitchen tests and I can add one. **however** this PR isn't meant to last. This whole thing needs a ground up re-write, and frankly, unless either the author of #9106 or lamont are going to actually do that, we should probably just *remove* this provider altogether. It doesn't work. I'm not even sure this will work reliably. Among other things it drops versions on the floor.... nothing here works as advertised, this just makes it not crash and at least attempt to install something.

At this point I'd almost rather just do:
```
execute 'snap install black' do
  not_if 'snap list | grep black'
end
```

for the 3 snaps I have to install. I guess what I"m saying is I can add a kitchen test that calls install (that's the ONLY thing that works at this point), or more, but I'm in no way going to take responsibility for making those tests work (only the simplest install case will work at this moment).

I actually pulled this monkey patch out of our cookbook at work and put the install into a shell script because I don't trust this provider at all, but I figured the least I could do is get *something* out so people who are following the attached bug might have some way forward.

**Comment by jaymzh** [comment]
I attempted to add kitchen tests, @tas50 , but it turns out that snap has some issues running in containers:
```
    status: Internal Server Error, kind: , message: system does not fully support snapd: cannot mount squashfs image using "squashfs": mount: /tmp/sanity-mountpoint-649535134: failed to setup loop device for /tmp/sanity-squashfs-413258619.
```

I know that loopback mounts _can_ work in containers, but no idea what needs to be done to make it so.

**Comment by jaymzh** [comment]
huh I take it back, looks like it worked on Azure. Won't look a gift horse in the mouth. Woot.

**Comment by jaymzh** [comment]
@tas50 to aisle 5

**Comment by tas50** [comment]
@jaymzh Can you rebase it and fix the failing spec?

**Comment by jaymzh** [comment]
yeah if you're happy with the kitchentest

**Comment by jaymzh** [comment]
rebased, fixed specs.

**Comment by tas50** [comment]
I'll nuke the kitchen tests out later since it turns out that doesn't work in docker atm.
