### PR TITLE
Fix failing tests on Solaris / Enable Solaris builds again

### LINKED ISSUE #10616: Resolve failures preventing us from enabling Solaris builds again
```
Failures:
  1) chef-client when the chef repo has a cookbook with a no-op recipe and a config file under .chef/knife.rb should load .chef/knife.rb when -z is specified
     Failure/Error: expect(result.stdout).to include("xxx")
       expected "[2020-11-10T19:15:58+00:00] WARN: No config file found or specified on command line. Using command line options instead.\nStarting Chef Infra Client, version 16.7.31\nPatents: https://www.chef.io/patents\n[2020-11-10T19:15:59+00:00] WARN: Run List override has been provided.\n[2020-11-10T19:15:59+00:00] WARN: Original Run List: []\n[2020-11-10T19:15:59+00:00] WARN: Overridden Run List: [recipe[x::default]]\nresolving cookbooks for run list: [\"x::default\"]\nSynchronizing Cookbooks:\n  - x (0.0.0)\nInstalling Cookbook Gems:\nCompiling Cookbooks...\nConverging 0 resources\n[2020-11-10T19:15:59+00:00] WARN: Skipping final node save because override_runlist was given\n\nRunning handlers:\nRunning handlers complete\nChef Infra Client finished, 0/0 resources updated in 00 seconds\n" to include "xxx"
       Diff:
       @@ -1,2 +1,18 @@
       -xxx
       +[2020-11-10T19:15:58+00:00] WARN: No config file found or specified on command line. Using command line options instead.
       +Starting Chef Infra Client, version 16.7.31
       +Patents: https://www.chef.io/patents
       +[2020-11-10T19:15:59+00:00] WARN: Run List override has been provided.
       +[2020-11-10T19:15:59+00:00] WARN: Original Run List: []
       +[2020-11-10T19:15:59+00:00] WARN: Overridden Run List: [recipe[x::default]]
       +resolving cookbooks for run list: ["x::default"]
       +Synchronizing Cookbooks:
       +  - x (0.0.0)
       +Installing Cookbook Gems:
       +Compiling Cookbooks...
       +Converging 0 resources
       +[2020-11-10T19:15:59+00:00] WARN: Skipping final node save because override_runlist was given
       +
       +Running handlers:
       +Running handlers complete
       +Chef Infra Client finished, 0/0 resources updated in 00 seconds
     # ./spec/integration/client/client_spec.rb:102:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:305:in `block (2 levels) in <top (required)>'
```

### PR DESCRIPTION
**Pull request by mwrock**
fixes #10616 

On Solaris, setting `Mixlib::ShellOut`'s `:cwd` does not update the `pwd` environment variable. Based on some follow up research I could not find evidence that the `pwd` environment variable is guaranteed to reflect the `pwd` command. It feels like there might be a cleaner approach here - like just using `Dir.pwd` across the board. I'd think that should work everywhere. However there may be a reason (and perhaps a good one, or not) why we prefer the environment variable.

Signed-off-by: mwrock <matt@mattwrock.com>

### CODE REVIEW

File: chef-config/lib/chef-config/workstation_config_loader.rb [hunk 1]
```diff
@@ -142,6 +142,8 @@ def locate_local_config
     def working_directory
       if ChefUtils.windows?
         env["CD"]
+      elsif RUBY_PLATFORM.include?("solaris")
```
Comment (tas50) [inline chef-config/lib/chef-config/workstation_config_loader.rb:145]:
```suggestion
      elsif ChefUtils.solaris2?
```

**Review by tas50 — CHANGES_REQUESTED** [review]
