### PR TITLE
Fix for knife bootstrap inheritance issue with knife plugins

### LINKED ISSUE #8583: knife bootstrap options are not getting inherited in knife plugins
## Description

In knife plugins when we are inheriting the `Chef::Knife::Bootstrap` class it should inherit all options but that's not happening and we are duplicating / re-defining all the options.
## Chef Version

Chef Infra Client: 15.0.303

## Platform Version

Doesn't matter
## Replication Case

I tried creating new class in knife-ec2  just to test what's going wrong. 
my ec2_server_test.rb
```
class Chef
  class Knife
    class Ec2ServerTest < Chef::Knife::Bootstrap
      banner "knife ec2 server test (options)"
    end
  end
end
```
running knife ec2 server test --help

## Client Output

```

```

## Stacktrace

output of the knife ec2 server test --help

```bundle exec knife ec2 server test --help
knife ec2 server test (options)
    -s, --server-url URL             Chef Infra Server URL.
        --chef-zero-host HOST        Host to start chef-zero on.
        --chef-zero-port PORT        Port (or port range) to start chef-zero on. Port ranges like 1000,1010 or 8889-9999 will try all given ports until one works.
    -k, --key KEY                    Chef Infra Server API client key.
        --[no-]color                 Use colored output, defaults to enabled.
    -c, --config CONFIG              The configuration file to use.
        --config-option OPTION=VALUE Override a single configuration option.
        --defaults                   Accept default values for all questions.
    -d, --disable-editing            Do not open EDITOR, just accept the data as is.
    -e, --editor EDITOR              Set the editor to use for interactive commands.
    -E, --environment ENVIRONMENT    Set the Chef Infra Client environment (except for in searches, where this will be flagrantly ignored).
        --[no-]fips                  Enable FIPS mode.
    -F, --format FORMAT              Which format to use for output.
        --[no-]listen                Whether a local mode (-z) server binds to a port.
    -z, --local-mode                 Point knife commands at local repository instead of Chef Infra Server.
    -u, --user USER                  Chef Infra Server API client username.
        --print-after                Show the data after a destructive operation.
        --profile PROFILE            The credentials profile to select.
    -V, --verbose                    More verbose output. Use twice for max verbosity.
    -v, --version                    Show Chef Infra Client version.
    -y, --yes                        Say yes to all prompts for confirmation.
    -h, --help                       Show this help message.
```
This is not listing all bootstrap options.

### PR DESCRIPTION
**Pull request by Vasu1105**
Signed-off-by: Vasu1105 <vasundhara.jagdale@msystechnologies.com>

## Description

This fixes the issue of inheritance of option with knife plugins as discussed in issue #8583
## Related Issue

Fixes #8583 
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

File: lib/chef/knife.rb [hunk 1]
```diff
@@ -88,6 +88,7 @@ def self.reset_subcommands!
     end
 
     def self.inherited(subclass)
+     super
```
Comment (tyler-ball) [inline lib/chef/knife.rb]: By calling `super` we are leveraging the options inheritance behavior that [mixlib-cli](https://github.com/chef/mixlib-cli/blob/2e77705cc598188ad80d6130df79ffb19781fb18/lib/mixlib/cli.rb#L44) has. @tas50 @lamont-granquist Do y'all know of any issues this will cause? If it will we can instead switch do doing the options merging that other classes were doing.

The removal of those from other files is because they are no longer necessary. This default behavior of inheriting options _seems_ more correct to me.

Comment (tyler-ball) [reply lib/chef/knife.rb]: @Vasu1105 CI is failing because of ChefStyle - this `super` needs 1 more space in front of it

Comment (Vasu1105) [reply lib/chef/knife.rb]: Thank you @tyler-ball. Fixed the chef style.
