### PR TITLE
windows_service: don't update the service if the run_as_user ca…

### LINKED ISSUE #8715: Incorrect casing on run_as_user cases windows_service to restart every run
## Description

When using the `windows_service` resource, if the `run_as_user` property differs only by case, chef will attempt to apply the change and restart the service so that it takes effect. Unfortunately, Windows does not store the casing change as the value is case-insensitive. This results in Chef attempting to make the change every time it runs (thus restarting the service).

In our case, this meant the service was only online for 15 minutes at a time. To resolve this, we had to change the credentials to another user account, then change them back with the casing Chef expected.

## Chef Version

Chef: 14.2.0

## Platform Version

Windows Server 2016

## Replication Case

1. Ensure a Windows Service exists which runs as a user account. Ensure the credentials are entered in all lowercase.
2. Create a Chef recipe which includes a `windows_service` resource. Specify the same credentials in the resource definition but use all upper case.
3. Run the cookbook multiple times, the service will be restarted on each run.

## Client Output

Client output cannot be included as it contains a password but was identical on each run. The windows_service resource was configured with a new username and password and then restarted.

## Stacktrace

No error is thrown.

### PR DESCRIPTION
**Pull request by jasonwbarnett**
## Description

Fixes #8715 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I have run the pre-merge tests locally and they pass.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by jasonwbarnett** [comment]
@tas50 ready for 👀

File: spec/unit/provider/service/windows_spec.rb [hunk 1]
```diff
@@ -19,9 +19,17 @@
 
 require "spec_helper"
 
-describe Chef::Provider::Service::Windows, "load_current_resource", :windows_only do
+describe Chef::Provider::Service::Windows, "load_current_resource" do
   include_context "Win32"
 
+  before(:all) do
+    Chef::ReservedNames::Win32::Security = Class.new unless windows?
```
Comment (jasonwbarnett) [inline spec/unit/provider/service/windows_spec.rb]: This goodness allows running this in *nix

File: spec/unit/provider/service/windows_spec.rb [hunk 2]
```diff
@@ -19,9 +19,17 @@
...
+  end
+
+  after(:all) do
+    Chef::ReservedNames::Win32.send(:remove_const, :Security) unless windows?
```
Comment (jasonwbarnett) [inline spec/unit/provider/service/windows_spec.rb]: This goodness allows running this in *nix
