### PR TITLE
Fix cron_d job name character set

### LINKED ISSUE #12165: `cron_d` resources with a space character in the resource name are not executed.
## Description

`cron_d` resources with a space character in the resource name are not executed.

## Chef Version

16.16.13

## Platform Version

Debian 11

## Replication Case

Assume the following `cron_d` ressource.

```ruby
cron_d 'so something' do
  command '/usr/bin/dosomething'

  hour   '0'
  minute '10'
end
```

It creates a file `/etc/cron.d/do something` which contains a space character.
As specified in the manpage this name is invalid.

> Additionally, cron reads the files in /etc/cron.d [...] Files must conform to the
> same naming convention as used by run-parts(8): they must consist solely of
> upper- and lower-case letters, digits, underscores, and hyphens.

So the cron job is not executed.

I would like to propose to validate the resource name of `cron_d` resources according
to the above character set.

## Client Output

not applicable

## Stacktrace

not applicable

### PR DESCRIPTION
**Pull request by hamarituc**
This commit restrict the `cron_d` job name property to the character set
according to the cron specification:

> Additionally, cron reads the files in /etc/cron.d [...] Files must
> conform to the same naming convention as used by run-parts(8): they
> must consist solely of upper- and lower-case letters, digits,
> underscores, and hyphens.

closes #12165

Signed-off-by: Mario Haustein <mario.haustein@hrz.tu-chemnitz.de>

## Description

The `cron_d` resource allows some special characters which aren't allowed.
This lets cron ignore the cron jobs silenty.

## Related Issue

- #12165 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I have run the pre-merge tests locally and they pass.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by lamont-granquist** [comment]
This runs on other platforms and I've got a concern that if stuff like AIX or Solaris or FreeBSD have implmented /etc/cron.d (and offhand I just haven't tracked this and don't know if they have in the past years) that they may not be using run-parts and this may be a linuxism, and that some people may be happily using something like umlauts in their cronjob filenames.  We definitely need to at least consider operating systems beyond linux.

And we've been bitten quite hard by these kinds of regex issues before, in the user and group providers and ultimately had to rip them out because users wanting UTF-8 usernames and the list of actually banned characters was quite small and distro-dependent and we broke a lot of people trying to do things that their distro supported.

Googling around it looks like Solaris and AIX probably do not have /etc/cron.d

FreeBSD does have /etc/cron.d but it isn't clear from the manpage what is supported:

https://www.freebsd.org/cgi/man.cgi?query=cron&apropos=0&sektion=8&manpath=FreeBSD+13.0-RELEASE+and+Ports&arch=default&format=html

**Comment by hamarituc** [comment]
Is there a way to apply different regex patterns depending on the platform? This might be a better solution. But I am not an expert to the chef core and can't see how to do it, in case it's possible.

This PR was just a first try from myself to fix the issue #12165, since I didn't receive any feedback on it. Nevertheless the issue should be fixed in some way, since it lets you create a erroneous `cron_d`-resources which are silently ignored by both chef and cron.

File: lib/chef/resource/cron/cron_d.rb [hunk 1]
```diff
@@ -115,14 +115,25 @@ def after_created
...
 
+      def validate_name
+        # ensure valid cron job names for linux, otherwise the jobs won't be executed
+        if linux?
+          unless cron_name =~ /^[a-zA-Z0-9_-]+$/
+            raise ArgumentError, "The cron job name should contain letters, numbers, hyphens and underscores only."
+          end
+        end
+      end
+
```
Comment (jaymzh) [inline lib/chef/resource/cron/cron_d.rb:126]: why isn't this in `validate_resource_requirements` ? That is exactly what that is for, no?

**Review by jaymzh — CHANGES_REQUESTED** [review]
I think this is probably better in `define_resource_requirements`

File: lib/chef/resource/cron/cron_d.rb (hunk 1 above)
Comment (hamarituc) [reply lib/chef/resource/cron/cron_d.rb]: Thanks for the suggestion. I was not aware of `define_resource_requirements` and fixed it.

**Review by jaymzh — APPROVED** [review]
Thanks!

**Review by marcparadise — APPROVED** [review]

**Review by PrajaktaPurohit — APPROVED** [review]

**Comment by PrajaktaPurohit** [comment]
This would probably need a rebase with main to get the tests passing again.

**Comment by hamarituc** [comment]
> @hamarituc Could you rebase to latest main?

:heavy_check_mark: done
