### PR TITLE
Escape string inside regex

### LINKED ISSUE #3055: Failure to print resource error message on Windows
### Version:
Chef-Client 12.1.0

### Environment:
Windows Server 2012 R2

### Scenario:
Execute a chef-solo run & view the chef log

### Steps to Reproduce:
Add an resource with a forced error, where the cookbooks are in a subdirectory starting with "p" like "C:\Windows\Temp\packer\cookbooks"

### Expected Result:
Get the nice display listing the source code of the resource & its values

### Actual Result:
C:/opscode/chef/embedded/apps/chef/lib/chef/formatters/error_inspectors/resource_failure_inspector.rb:66: warning: invalid Unicode Property \p

What I think is happening is that the "file" variable in the below line has Windows back-slashes.  Hence when used as a regex direct (without other processing or escaping) parts will be interpreted as special escape codes & so block the desired functionality.  Not sure but would hope there's an easy way in ruby to regex-escape an arbitrary string.

https://github.com/chef/chef/blob/master/lib/chef/formatters/error_inspectors/resource_failure_inspector.rb#L66

### PR DESCRIPTION
**Pull request by jdmundrawala**
Should fix #3055
The unit tests repros the issue, but does not fail. Ruby seems to be logging a warning somewhere internally

### CODE REVIEW

**Comment by jdmundrawala** [comment]
and probably also https://github.com/chef/chef/issues/3343, however I'm not 100% sure about that

**Comment by thommay** [comment]
LGTM :+1:

File: lib/chef/formatters/error_inspectors/resource_failure_inspector.rb [hunk 1]
```diff
@@ -63,7 +63,7 @@ def add_explanation(error_description)
         def recipe_snippet
           return nil if dynamic_resource?
           @snippet ||= begin
-            if file = resource.source_line[/^(([\w]:)?[^:]+):([\d]+)/,1] and line = resource.source_line[/^#{file}:([\d]+)/,1].to_i
+            if file = resource.source_line[/^(([\w]:)?[^:]+):([\d]+)/,1] and line = resource.source_line[/^#{Regexp.escape(file)}:([\d]+)/,1].to_i
```
Comment (stevendanna) [inline lib/chef/formatters/error_inspectors/resource_failure_inspector.rb]: :+1: on the change in general.  If you have some time to clean this up a bit, it might be nice to refactor this into well-named functions.

Comment (jdmundrawala) [inline lib/chef/formatters/error_inspectors/resource_failure_inspector.rb]: refactored

**Comment by stevendanna** [comment]
:+1:

**Comment by thommay** [comment]
@jdmundrawala please update the changelog :)

**Comment by rojomisin** [comment]
I'm using vagrant testing a windows cookbook using 12.3 chef-client, is there a workaround?  Do I have to build my own chef-client, and if so how do I tell vagrant and/or chef-dk to use it (it always pulls from downloads repo).

**Comment by lonniev** [comment]
Same plea as @rojomisin : it's great to here this is fixed and now when will it be released?

**Comment by lonniev** [comment]
Would be sweet if:

```ruby
  config.omnibus.chef_version = '12.4.0.rc.0'
```

worked. It tries to but gets a messy 404 when trying to download that revision.

There a suggestions online for running a shell provisioner to gem install particular chef solo versions. I'll try that advice.

**Comment by jdmundrawala** [comment]
@lonniev not sure what tool you are using, but i think if you can specifiy `prerelease` to be true, it will work. You might also have to change `chef_version` to be 12.4.0:
https://www.getchef.com/chef/metadata?v=12.4.0&prerelease=true&nightlies=false&p=el&pv=6&m=x86_64

**Comment by lonniev** [comment]
Here's the Windows shell provisioner approach:

```ruby
    vmh.vm.provision :shell, :inline => "choco install ruby -fy"
    vmh.vm.provision :shell, :inline => "choco install rubygems -fy"

    vmh.vm.provision :shell, :inline => "gem install chef --version 12.4.0.rc.0 --no-rdoc --no-ri --conservative"
```

This tactic runs into the Ruby Gems SSL issue:

```shell
==> vb-tt-sync: ERROR:  Could not find a valid gem 'chef' (= 12.4.0.rc.0), here is why:
==> vb-tt-sync:           Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)
```

I'll try @jdmundrawala's :prerelease suggestion.

**Comment by lonniev** [comment]
Here's the hope:

https://docs.chef.io/install_omnibus.html

And now to figure out how to pass arguments to the vagrant omnibus handler. ( Options -p and -s are needed. )

**Comment by lonniev** [comment]
Looks like the omnibus code will pass along anything given as the version string:

```ruby
            if windows_guest?
              install_cmd = "cmd.exe /c #{install_script_name} #{version}"
```

and so this might work:

```ruby
    config.omnibus.chef_version = '12.4.0.rc.0 -p -s'
```

**Comment by jdmundrawala** [comment]
ew, but ok. if it get's you moving forward. Ill see about fixing up omnitruck

**Comment by lonniev** [comment]
Not yet. The string is getting parsed for supported versions. I need to read that code more closely.

Also, it looks like I could curl install chef using a shell provisioner line for what the Chef Omnibus link offers.

**Comment by lonniev** [comment]
Any advice on what is the URL to the prerelease versions? I don't see a way to get vagrant omnibus to go fetch it and the chef site does its best to redirect me to the 12.3.0 latest release.

**Comment by lonniev** [comment]
This looked promising but I don't see any msi installers within it. At least it suggests that the 12.4.0 RC versions are somewhere available:

https://opscode-omnibus-packages.s3.amazonaws.com/

**Comment by lonniev** [comment]
Even better: https://docs.chef.io/api_omnitruck.html

**Comment by lonniev** [comment]
Here it is:

```bash
$ curl -H "Accept: application/json" 'http://www.chef.io/chef/metadata?p=windows&v=2012&m=x86_64&v=latest&prerelease=true'
{
  "relpath": "/windows/2008r2/x86_64/chef-client-12.4.0-rc.0-1.msi",
  "md5": "3e5b1de34c6d8b373cdecee87018a64c",
  "sha256": "346196b526bdd09e5ea550711addaa0ff87d524c99dbcb4c5adc600cea5c9903",
  "url": "http://opscode-omnibus-packages.s3.amazonaws.com/windows/2008r2/x86_64/chef-client-12.4.0-rc.0-1.msi"
}
```

**Comment by lonniev** [comment]
Here's a machine-specific working config snippet:

```ruby
  config.omnibus.install_url = "http://opscode-omnibus-packages.s3.amazonaws.com/windows/2008r2/x86_64/chef-client-12.4.0-rc.0-1.msi"
  config.omnibus.chef_version = "12.4.0.rc.0"
```

**Comment by lonniev** [comment]
Interesting. All this time, here's the reason my choco resources were failing:

```bash
==> vb-tt-sync: [2015-06-03T16:16:57-07:00] FATAL: RuntimeError: chocolatey[wget] (chocolatey-wget::default line 28) had an error: RuntimeError: Wrong package name wget != Wget
```

The good news is that the darn Regex parsing error in the windows pathname for the recipe is gone.

**Comment by lonniev** [comment]
I probably could revert to chef-solo :latest now, knowing that the exception behind the exception is an overly careful check in the Chocolatey recipe.

**Comment by rojomisin** [comment]
thanks for digging into this @lonniev , I worked around by going back to 11, but I'll try the install_url/chef_version config snippet you posted above.
