### PR TITLE
Fix idempotency issues with network mounts

### LINKED ISSUE #11255: Enabling network mounts with a root of / not idempotent and the / is stripped out
## Description

Enabling network (nfs) mounts with a root of `/` is not idempotent and the `/` is getting striped. The result is a new `fstab` entry every run. Specifying a root other than `/` works fine. The problem occurs when the device is like `something:/`

## Chef Version

```
# chef-client  --version
Chef Infra Client: 16.11.7
```

Looks like there's been several PRs dealing with `/` root on network devices.

I did some bisecting and found the problem was introduced in https://github.com/chef/chef/commit/7fe69a2a865e24314540e2c8a9c0d28375b22eed. 

As of https://github.com/chef/chef/commit/c600ba4886fd5ab9af333f57ae95d5ed6a71164b the `/` was getting stripped out but the fstab update was idempotent. With https://github.com/chef/chef/commit/950a3e4e7c85ccdc88162f89a7f6eba8807f02d7 it reverted back to the fstab update not being idempotent and still stripping the `/`.

## Platform Version

Debian 10

## Replication Case

Can repro with a simple `chef-apply` script:

```
mount '/tmp/foo' do
  device 'something:/'
  fstype 'nfs4'
  options 'defaults'
  pass 0
  action [:enable]
end

```

## Client Output

```
# chef-apply mounttest.rb  
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * mount[/tmp/foo] action enable
    - enable something:/
```
Running it again results in the same output. `/etc/fstab` contains multiple entries with the `/` stripped off:

```
something: /tmp/foo nfs4 defaults 0 0
something: /tmp/foo nfs4 defaults 0 0
```

### PR DESCRIPTION
**Pull request by ramereth**
Resolves #11255

This is basically a continuation of #11031 where I fixed it in one place but then created a regression with idempotency as noted in #11255. This ensures that the /etc/fstab file actually gets the output we expect with network mounts using a root device.

Signed-off-by: Lance Albertson <lance@osuosl.org>

### CODE REVIEW

**Comment by ramereth** [comment]
@tas50 @lamont-granquist I don't think the failures on related to my change but please take a look at this. I'll backport to chef-16 if you approve.

**Comment by tas50** [comment]
@ramereth is there a reasonable way to write a unit test here?

**Comment by ramereth** [comment]
@tas50 probably, let me look into it

File: lib/chef/provider/mount.rb [hunk 1]
```diff
@@ -176,7 +176,12 @@ def wait_until_unmounted(tries)
       # Returns the new_resource device as per device_type
       def device_fstab
         # Removed "/" from the end of str, because it was causing idempotency issue.
```
Comment (tas50) [inline lib/chef/provider/mount.rb:178]: Can you expand this comment a bit since we're beyond the single chomp scenario described there

**Review by jaymzh — APPROVED** [review]

**Comment by tas50** [comment]
Thanks @ramereth.

**Comment by tas50** [comment]
@ramereth we still have the specs for that so if those are accurate we should keep that behavior. While this whole back and forth mess has been unfortunate for stability, it has allowed us to better build out the use cases via specs so we make sure we build something that solves all the problems.
