### PR TITLE
Functional tests: Ensure we logon with the local security_user account

### LINKED ISSUE #7440: Functional test failure for Chef::Win32::Security when running with Administrative token on Windows 10
```
 21) Chef::Win32::Security running as non admin user has_admin_privileges? returns false
      Failure/Error:
        has_admin_privileges = with_user_context(user, password, domain, :local) do
          Chef::ReservedNames::Win32::Security.has_admin_privileges?
        end

      RuntimeError:
        Attempted to set the user context before opening a session.
      # ./lib/chef/util/windows/logon_session.rb:123:in `validate_session_open!'
      # ./lib/chef/util/windows/logon_session.rb:63:in `close'
      # ./lib/chef/mixin/user_context.rb:47:in `ensure in with_user_context'
      # ./lib/chef/mixin/user_context.rb:47:in `with_user_context'
      # ./spec/functional/win32/security_spec.rb:57:in `block (3 levels) in <top (required)>'
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:254:
in `instance_exec'
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:254:
in `block in run'
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:500:
in `block in with_around_and_singleton_context_hooks'
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:457:
in `block in with_around_example_hooks'
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:466:in
 `block in run'
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:604:in
 `run_around_example_hooks_for'
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:466:in
 `run'
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:457:
in `with_around_example_hooks'
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:500:
in `with_around_and_singleton_context_hooks'
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:251:
in `run'
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.r
b:628:in `block in run_examples'
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.r
b:624:in `map'
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.r
b:624:in `run_examples'
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.r
b:590:in `run'
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.r
b:591:in `block in run'
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.r
b:591:in `map'
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.r
b:591:in `run'
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:118:i
n `block (3 levels) in run_specs'
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:118:i
n `map'
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:118:i
n `block (2 levels) in run_specs'
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/configuration.r
b:1926:in `with_suite_hooks'
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:113:i
n `block in run_specs'
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:79:
in `report'
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:112:i
n `run_specs'
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:87:in
 `run'
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:71:in
 `run'
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:45:in
 `invoke'
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/exe/rspec:4:in `<top (required
)>'
      # C:/Ruby25-x64/bin/rspec:23:in `load'
      # C:/Ruby25-x64/bin/rspec:23:in `<main>'
      # ------------------
      # --- Caused by: ---
      # Chef::Exceptions::Win32APIError:
      #   Logon for user `security_user` failed with Win32 status 1326.
      #   ./lib/chef/util/windows/logon_session.rb:56:in `open'
```

### PR DESCRIPTION
**Pull request by stuartpreston**
Signed-off-by: Stuart Preston <stuart@chef.io>

### Description

This resolves the functional test failures so they work on an Azure AD-connected Windows 10 or Windows 2016 machine.  Our tests always create a "local" user however the domain name on an AAD connected machine is the NetBIOS name of the domain (e.g. OPSCODECORP).

### Issues Resolved

Fixes #7440 

### Check List

- [ ] New functionality includes tests
- [ ] All tests pass
- [ ] RELEASE\_NOTES.md, has been updated if required (not required for bugfixes, required for API changes)
- [ ] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

### CODE REVIEW

File: spec/functional/win32/security_spec.rb [hunk 1]
```diff
@@ -34,10 +34,7 @@
     let(:password) { "Security@123" }
 
     let(:domain) do
-      whoami = Mixlib::ShellOut.new("whoami")
-      whoami.run_command
-      whoami.error!
-      whoami.stdout.split("\\")[0]
+      ENV['COMPUTERNAME']
```
Comment (tas50) [inline spec/functional/win32/security_spec.rb]: ' -> " for Chefstyle here
