### PR TITLE
Ensure that a search query makes progress

### LINKED ISSUE #3099: knife search and DSL search() method hangs
I'm investigating upgrading from chef-client 11.16.4 to 12.1.0 and am seeing a change in behaviour in how knife search and the DSL search method works.

The server is Open Source Chef Server 11.1.1. 

When searching for one of our data bags, chef-client and knife 12 get stuck in infinite recursion and bail with a StackLevelTooDeep error. I believe this is because of the way default arguments are set for the search method in Chef 12. 

The problem is specific to a few of our data bags. In each case, the "total" count returned by /search is incorrect. There's only one item in the data bag, but the server reports a total of 35 items in it's response. This causes knife to repeat the ```/search``` request (I assume because it's expecting more items).

In the snippet below, the default for ```args_h[:rows]``` is ```nil```. This means that start never gets incremented. Combined with ```response["rows"].length``` always being 1 (there's a single item in the data bag), and ```response["total"]``` being 35 (I'm not sure where this total is coming from, I suspect a corrupt index on the Chef server), ```search()``` is called recursively with the same arguments until the stack overflows.

Adding ```--rows 1000``` to the knife command restores the functionality present in knife 11 (1000 was the default). The DSL search method requires the additional rows parameter to be set as well in order for it to work. See the code snippet below for more information.

https://github.com/chef/chef/blob/8261791ced25227781f0d0ad3f44ef77c889d53b/lib/chef/search/query.rb
```ruby
def search(type, query='*:*', *args, &block)
        validate_type(type)

        args_h = hashify_args(*args)
        response = call_rest_service(type, query: query, **args_h)

        if block
          response["rows"].each { |row| block.call(row) if row }
          unless (response["start"] + response["rows"].length) >= response["total"]
            args_h[:start] = response["start"] + (args_h[:rows] || 0)
            search(type, query, args_h, &block)
          end
          true
        else
          [ response["rows"], response["start"], response["total"] ]
        end
end
```

### PR DESCRIPTION
**Pull request by tomhughes**
If a search doesn't return a full result, and there was no row
limit specified, then increment the start pointer by the number
of rows returned, not zero.

This should fix #3099

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @tomhughes

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

File: lib/chef/search/query.rb [hunk 1]
```diff
@@ -89,7 +89,7 @@ def search(type, query='*:*', *args, &block)
         if block
           response["rows"].each { |row| block.call(row) if row }
           unless (response["start"] + response["rows"].length) >= response["total"]
-            args_h[:start] = response["start"] + (args_h[:rows] || 0)
+            args_h[:start] = response["start"] + (args_h[:rows] || response["rows"].length)
```
Comment (stevendanna) [inline lib/chef/search/query.rb]: I would always just look at response["rows"].length.

Comment (tomhughes) [inline lib/chef/search/query.rb]: Well I did wonder if that wasn't a better plan... Happy to change it if you want?

**Comment by stevendanna** [comment]
@tomhughes Thanks for this.  Let's go ahead and only loog at response["rows".length as that feels like the correct behavior. Would you mind adding a test to cover this behavior?  If you aren't familiar with rspec, I've created an example that may work for you.  Here is the diff:

```
diff --git a/spec/unit/search/query_spec.rb b/spec/unit/search/query_spec.rb
index 2fb197b..fa042ca 100644
--- a/spec/unit/search/query_spec.rb
+++ b/spec/unit/search/query_spec.rb
@@ -81,6 +81,9 @@ describe Chef::Search::Query do
   end

   describe "search" do
+    let(:query_string) { "search/node?q=platform:rhel&sort=X_CHEF_id_CHEF_X%20asc&start=0" }
+    let(:query_string_continue) { "search/node?q=platform:rhel&sort=X_CHEF_id_CHEF_X%20asc&start=4" }
+
     let(:response) { {
       "rows" => [
         { "name" => "my-name-is-node",
@@ -140,6 +143,19 @@ describe Chef::Search::Query do
       "total" => 4
     } }

+    let(:big_response) {
+      r = response.dup
+      r["total"] = 8
+      r
+    }
+
+    let(:big_response_end) {
+      r = response.dup
+      r["start"] = 4
+      r["total"] = 8
+      r
+    }
+
     it "accepts a type as the first argument" do
       expect { query.search("node") }.not_to raise_error
       expect { query.search(:node) }.not_to raise_error
@@ -195,6 +211,15 @@ describe Chef::Search::Query do
       query.search(:node, "*:*", sort: nil, start: 0, rows: 1) { |r| @call_me.do(r) }
     end

+    it "sends multiple API requests when the server indicates there is more data" do
+      expect(rest).to receive(:get_rest).with(query_string).and_return(big_response)
+      expect(rest).to receive(:get_rest).with(query_string_continue).and_return(big_response_end)
+      query.search(:node, "platform:rhel") do |r|
+        nil
+      end
+    end
+
+
```

**Comment by tomhughes** [comment]
I've updated my fix now, and added your tests.

**Comment by stevendanna** [comment]
:+1:

**Comment by thommay** [comment]
This seems reasonable :+1:

**Comment by btm** [comment]
:+1:

**Comment by ranjib** [comment]
:+1:

File: lib/chef/search/query.rb [hunk 2]
```diff
@@ -89,7 +89,7 @@ def search(type, query='*:*', *args, &block)
         if block
           response["rows"].each { |row| block.call(row) if row }
           unless (response["start"] + response["rows"].length) >= response["total"]
```
Comment (abriel) [inline lib/chef/search/query.rb]: Is it possible to have the following condition: ?
unless ((response["start"] + response["rows"].length) >= response["total"]) || (response["rows"].length == 0)
Any background issues? 
In case if index is corrupted on chef-server (returns not correct total) It will help.
Thanks.

Comment (btm) [inline lib/chef/search/query.rb]: Since this PR was already merged, you're unlikely to have many people see this comment, if any more than me.

If you have a test case that you could reproduce where this would be a problem, I'd recommend starting with creating an issue. If you're just thinking, I'd go to the [chef](http://lists.opscode.com/sympa/info/chef) or [chef-dev](http://lists.opscode.com/sympa/info/chef-dev) mailing list.
