### PR TITLE
windows_task resource: Allow non-system users without password

### LINKED ISSUE #7834: windows_task incorrectly requires password when defining a task for the current user
## Description
windows_task

## Chef Version
14.5.33

## Platform Version
Windows 10

## Replication Case
A scheduled task can be successfully defined (and runs) using the "schtasks" command via a powershell_script resource:
```
powershell_script 'gitbackup-schtasks' do
  cwd 'C:/bjsdev'
  code <<-EOH
    schtasks /CREATE /TN "gitbackup" /F /SC "daily" /MO "1" /ST "12:21" /TR "powershell -NonInteractive -File C:/bjsdev/tools/backup_git_repos.ps1" /RU "#{ENV['USERDOMAIN']}\\#{ENV['USERNAME']}"
  EOH
end
```

However when I try to define the task using the windows_task resource, I get the error referenced in the Client Output.
```
windows_task 'gitbackup' do
  command 'powershell -NonInteractive -File "C:/bjsdev/tools/backup_git_repos.ps1"'
  cwd 'C:/bjsdev'
  force true
  frequency :daily
  start_time '12:21'
  user "#{ENV['USERDOMAIN']}\\#{ENV['USERNAME']}"
end
```

## Client Output
```
ArgumentError
-------------
Cannot specify a user other than the system users without specifying a password!. Valid passwordless users: 'NT AUTHORITY\SYSTEM', 'SYSTEM', 'NT AUTHORITY\LOCALSERVICE', 'NT AUTHORITY\NETWORKSERVICE', 'BUILTIN\USERS', 'USERS'
```

## Stacktrace
```
Generated at 2018-10-31 16:09:07 -0400
ArgumentError: Cannot specify a user other than the system users without specifying a password!. Valid passwordless users: 'NT AUTHORITY\SYSTEM', 'SYSTEM', 'NT AUTHORITY\LOCALSERVICE', 'NT AUTHORITY\NETWORKSERVICE', 'BUILTIN\USERS', 'USERS'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33-universal-mingw32/lib/chef/resource/windows_task.rb:226:in `validate_user_and_password'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33-universal-mingw32/lib/chef/resource/windows_task.rb:140:in `after_created'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33-universal-mingw32/lib/chef/resource_builder.rb:73:in `build'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33-universal-mingw32/lib/chef/dsl/declare_resource.rb:314:in `build_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33-universal-mingw32/lib/chef/dsl/declare_resource.rb:271:in `declare_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33-universal-mingw32/lib/chef/dsl/resources.rb:38:in `windows_task'
C:/bjsdev/bootstrap/cache/cookbooks/kickstart/recipes/windows.rb:182:in `from_file'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33-universal-mingw32/lib/chef/mixin/from_file.rb:34:in `instance_eval'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33-universal-mingw32/lib/chef/mixin/from_file.rb:34:in `from_file'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33-universal-mingw32/lib/chef/cookbook_version.rb:199:in `load_recipe'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33-universal-mingw32/lib/chef/run_context.rb:350:in `load_recipe'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33-universal-mingw32/lib/chef/run_context.rb:306:in `block in include_recipe'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33-universal-mingw32/lib/chef/run_context.rb:305:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33-universal-mingw32/lib/chef/run_context.rb:305:in `include_recipe'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33-universal-mingw32/lib/chef/dsl/include_recipe.rb:26:in `include_recipe'
C:/bjsdev/bootstrap/cache/cookbooks/kickstart/recipes/default.rb:4:in `from_file'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33-universal-mingw32/lib/chef/mixin/from_file.rb:34:in `instance_eval'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33-universal-mingw32/lib/chef/mixin/from_file.rb:34:in `from_file'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33-universal-mingw32/lib/chef/cookbook_version.rb:199:in `load_recipe'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33-universal-mingw32/lib/chef/run_context.rb:350:in `load_recipe'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33-universal-mingw32/lib/chef/run_context.rb:306:in `block in include_recipe'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33-universal-mingw32/lib/chef/run_context.rb:305:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33-universal-mingw32/lib/chef/run_context.rb:305:in `include_recipe'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33-universal-mingw32/lib/chef/dsl/include_recipe.rb:26:in `include_recipe'
C:/bjsdev/bootstrap/cache/cookbooks/kickstart/recipes/tms4s_all.rb:3:in `from_file'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33-universal-mingw32/lib/chef/mixin/from_file.rb:34:in `instance_eval'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33-universal-mingw32/lib/chef/mixin/from_file.rb:34:in `from_file'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33-universal-mingw32/lib/chef/cookbook_version.rb:199:in `load_recipe'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33-universal-mingw32/lib/chef/run_context.rb:350:in `load_recipe'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:166:in `block in compile_recipes'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:163:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:163:in `compile_recipes'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:79:in `compile'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33-universal-mingw32/lib/chef/run_context.rb:199:in `load'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33-universal-mingw32/lib/chef/policy_builder/expand_node_object.rb:97:in `setup_run_context'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33-universal-mingw32/lib/chef/client.rb:515:in `setup_run_context'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33-universal-mingw32/lib/chef/client.rb:281:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33-universal-mingw32/lib/chef/application.rb:303:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33-universal-mingw32/lib/chef/application.rb:279:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33-universal-mingw32/lib/chef/application.rb:261:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33-universal-mingw32/lib/chef/application/client.rb:440:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33-universal-mingw32/lib/chef/application.rb:66:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33-universal-mingw32/bin/chef-client:25:in `<top (required)>'
C:/opscode/chef/bin/chef-client:75:in `load'
C:/opscode/chef/bin/chef-client:75:in `<main>'
```

### PR DESCRIPTION
**Pull request by Nimesh-Msys**
- Minor changes in validations under `validate_user_and_password` to handle this feature
- `validate_interactive_setting` would no longer be needed
- Simple changes in error verbiage
- Added test cases
- Fixes MSYS-924

Signed-off-by: Nimesh <nimesh.patni@msystechnologies.com>

### Description

- Non-System users would only need to provide a password for Non-Interactive tasks
- For interactive tasks, they may or may not provide a password
- System users always creates non-interactive tasks and password should not be sent

### Issues Resolved

#7834 

### Sub Task

[win32-taskscheduler](https://github.com/chef/win32-taskscheduler/pull/76) needs to be merged and updated for these changes.

### Check List

- [x] New functionality includes tests
- [x] All tests pass
- [x] RELEASE\_NOTES.md has been updated if required (not required for bugfixes, required for API changes)
- [x] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

### CODE REVIEW

File: spec/unit/resource/windows_task_spec.rb [hunk 1]
```diff
@@ -67,23 +67,61 @@
...
+          expect { resource.after_created }.to_not raise_error
+        end
+        it "raises an error when a password is given" do
+          resource.password "XXXX"
+          expect { resource.after_created }.to raise_error(ArgumentError, "Password is not required for system users.")
+        end
+      end
     end
 
-    it "does not raise an error if the user is a system user even if lowercase" do
```
Comment (Vasu1105) [inline spec/unit/resource/windows_task_spec.rb]: Why this one is removed ?

Comment (Nimesh-Msys) [reply spec/unit/resource/windows_task_spec.rb]: Added

**Comment by Nimesh-Msys** [comment]
Appveyor is failing for an expected reason. As we are now givin a support to interactive property and have added a parameter in set_account_information of win32-taskscheduler.
Once we merge [win32-taskscheduler](https://github.com/chef/win32-taskscheduler/pull/76), it would probably get resolved.
Specs are working fine with local changes in win32-taskscheduler gem.
