### PR TITLE
Change all accesses to ENV['HOME'] or ~ to PathHelper.home instead.

### LINKED ISSUE #2939: knife cookbook upload fails when user env:homedrive is a network share
The default knife.rb use ENV['HOME'] to determine where the .chef/checksums folder should be.  It appears that Ruby is concatenating HOMEDRIVE and HOMEPATH to get that location rather than using USERPROFILE.  If a users corporate HOMEDRIVE is a network share and not available, this causes knife cookbook upload to fail with an error that it cannot find that drive letter.

### PR DESCRIPTION
**Pull request by ksubrama**
Fixes #2939

### CODE REVIEW

**Comment by tyler-ball** [comment]
What is the desire behind doing this?

**Comment by btm** [comment]
@tyler-ball See #2939. ENV['HOME'] on Windows uses a "home directory" that is often on a network share and not accessible when you're on a laptop and out of the office. This is a really common enterprise situation.

File: lib/chef/shell.rb [hunk 1]
```diff
@@ -295,18 +296,19 @@ def parse_opts
     private
 
     def config_file_for_shell_mode(environment)
+      dot_chef_dir = Chef::Util::PathHelper.home('.chef')
       if config[:config_file]
         config[:config_file]
-      elsif environment && ENV['HOME']
+      elsif environment && dot_chef_dir
```
Comment (tyler-ball) [inline lib/chef/shell.rb]: It seems like this could be a breaking change - if `dot_chef_dir` didn't exist before it would hit the `exit 1` on line 307.

Comment (tyler-ball) [inline lib/chef/shell.rb]: It seems like this could be a breaking change.  If the home directory didn't exist before, it would `exit 1` on line 307.  Now it will skip to the next `elsif`

File: lib/chef/util/path_helper.rb [hunk 2]
```diff
@@ -142,6 +142,64 @@ def self.escape_glob(*parts)
...
       end
+
+      # Retrieves the "home directory" of the current user while trying to ascertain the existence
+      # of said directory.  The path returned uses / for all separators (the ruby standard format).
+      # If a set of path elements may be provided.  They are appended as-is to the home path if the
+      # homepath exists.  If the home directory doesn't exist or an error is otherwise encountered,
+      # nil is returned.  If an optional block is provided, the joined path is passed to that block
+      # if the home path is valid and the result of the block is returned.
+      def self.home(*args)
+        @@home_dir ||= self.all_homes { |p| break p }
```
Comment (tyler-ball) [inline lib/chef/util/path_helper.rb]: Why not just an instance variable?

File: lib/chef/util/path_helper.rb [hunk 3]
```diff
@@ -142,6 +142,64 @@ def self.escape_glob(*parts)
...
+          # HOMEDRIVE HOMEPATH
+          # USERPROFILE
+          # Ruby only checks to see if the variable is specified - not if the directory actually exists.
+          # On Windows, HOMEDRIVE HOMEPATH can point to a different location (such as an unavailable network mounted drive)
+          # while USERPROFILE points to the location where the user application settings and profile are stored.  HOME
+          # is not defined as an environment variable (usually).  If the home path actually uses UNC, then the prefix is
+          # HOMESHARE instead of HOMEDRIVE.
+          #
+          # We instead walk down the following and if that path actually exists, we pick and use that.  Once a home-path
+          # has been picked, that value is memoized so that subsequent calls to home_dir don't bounce around.
```
Comment (tyler-ball) [inline lib/chef/util/path_helper.rb]: I don't see the memoization here - I think it only occurs in `self.home`

File: lib/chef/util/path_helper.rb (hunk 2 above)
Comment (ksubrama) [inline lib/chef/util/path_helper.rb]: This was a class method and I don't have enough ruby fu to know how to cache this any other way.  I'm also not entirely sure I *want* to cache it.  When I initially wrote it, it made sense to me that repeated calls to home should return the same value and not require an fstat every single time.  But I'm not entirely sure we want a caching behavior.  I'm open to suggestions.

Comment (tyler-ball) [inline lib/chef/util/path_helper.rb]: Doh, it is a class method, I think @@ is fine.

The only danger I see from caching it is if the chef-client process is long running and the home directory is going to change.  That doesn't seem likely to me, but someone else may know better.

File: lib/chef/config.rb [hunk 4]
```diff
@@ -569,12 +569,8 @@ def self.env
       ENV
     end
 
-    def self.windows_home_path
```
Comment (jdmundrawala) [inline lib/chef/config.rb]: Was this publicly accessible?
If so, i recommend we start with a deprecation warning before removing

File: lib/chef/knife/core/subcommand_loader.rb [hunk 5]
```diff
@@ -28,8 +28,8 @@ class SubcommandLoader
       attr_reader :chef_config_dir
       attr_reader :env
 
-      def initialize(chef_config_dir, env=ENV)
```
Comment (jdmundrawala) [inline lib/chef/knife/core/subcommand_loader.rb]: changing this scares me

File: lib/chef/shell.rb (hunk 1 above)
Comment (ksubrama) [inline lib/chef/shell.rb]: ENV['HOME'] can be artificially set when the directory doesn't exist but I believe I went through all the instanced modified to check if it makes more sense if we should use an environment variable if that directory doesn't exist.  In this one instance, I did wonder whether the best check would actually be "elsif environment" and not check dot_chef_dir at all but again...  unsure.

File: lib/chef/util/path_helper.rb [hunk 6]
```diff
@@ -142,6 +142,64 @@ def self.escape_glob(*parts)
...
+          # USERPROFILE
+
+          paths << ENV['HOME']
+          paths << ENV['HOMEDRIVE'] + ENV['HOMEPATH'] if ENV['HOMEDRIVE'] && ENV['HOMEPATH']
+          paths << ENV['HOMESHARE'] + ENV['HOMEPATH'] if ENV['HOMESHARE'] && ENV['HOMEPATH']
+          paths << ENV['USERPROFILE']
+        end
+        paths << Dir.home
+
+        (paths.reduce([]) do |acc, home_path|
```
Comment (jdmundrawala) [inline lib/chef/util/path_helper.rb]: would filter not be more concise here?

File: lib/chef/util/path_helper.rb [hunk 7]
```diff
@@ -142,6 +142,64 @@ def self.escape_glob(*parts)
...
+          home_path = home_path.gsub(path_separator, ::File::SEPARATOR) if home_path
+          acc << home_path if home_path && Dir.exists?(home_path) && !acc.include?(home_path)
+          acc
+        end).map do |home_path|
+          joined_path = File.join(home_path, *args)
+          block_given? ? (yield joined_path) : joined_path
```
Comment (jdmundrawala) [inline lib/chef/util/path_helper.rb]: I don't understand what's happening here. What's wrong with just `joined_path`

File: spec/functional/file_content_management/deploy_strategies_spec.rb [hunk 8]
```diff
@@ -43,7 +43,7 @@ def normalize_mode(mode_int)
 
     ##
     # UNIX Context
-    let(:default_mode) { normalize_mode(0100666 - File.umask) }
```
Comment (jdmundrawala) [inline spec/functional/file_content_management/deploy_strategies_spec.rb]: This looks unrelated

File: spec/functional/resource/cookbook_file_spec.rb [hunk 9]
```diff
@@ -32,7 +32,7 @@
     content
   end
 
-  let(:default_mode) { ((0100666 - File.umask) & 07777).to_s(8) }
+  let(:default_mode) { (0666 & ~File.umask).to_s(8) }
```
Comment (jdmundrawala) [inline spec/functional/resource/cookbook_file_spec.rb]: unrelated?

File: lib/chef/shell.rb (hunk 1 above)
Comment (tyler-ball) [inline lib/chef/shell.rb]: I think `elsif environment` here is the right thing to preserve behavior.  I'll make comments on any other sections if I think they should be changed too.

File: spec/functional/file_content_management/deploy_strategies_spec.rb (hunk 8 above)
Comment (btm) [inline spec/functional/file_content_management/deploy_strategies_spec.rb]: These are from another PR, I presume he has them on this one because he needs them for the tests to pass on his workstation.

See https://github.com/chef/chef/pull/3086

File: lib/chef/util/path_helper.rb (hunk 6 above)
Comment (ksubrama) [inline lib/chef/util/path_helper.rb]: I couldn't find a filter method on Array or Enumerable.  Is this a method that gets patched in from somewhere?  I also used reduce because I was filtering out bad paths and dupes at the same time.  I'm also not sure if I'm doing the de-dup right - is there a way to canonicalize the path correctly (keep the slashes pointed the right way)?

Comment (smith) [inline lib/chef/util/path_helper.rb]: It's "select" http://ruby-doc.org/core-2.2.1/Enumerable.html#method-i-select (taken from Smalltalk)

File: lib/chef/util/path_helper.rb (hunk 7 above)
Comment (ksubrama) [inline lib/chef/util/path_helper.rb]: I was implementing allowing for an optional &block to be provided.  I don't know how idiomatic it is in ruby to do something like PathHelper.home {|p| puts(p) } - i.e. the provided block only gets called if a resource it needs is actually valid/alive.  I was modeling it off of the "with" clause in Python or the "using" clause in C#.

File: spec/functional/resource/cookbook_file_spec.rb (hunk 9 above)
Comment (ksubrama) [inline spec/functional/resource/cookbook_file_spec.rb]: Yes - please ignore.  It's there to make tests pass for me.

File: lib/chef/config.rb (hunk 4 above)
Comment (ksubrama) [inline lib/chef/config.rb]: It doesn't seem to be used anywhere else but here as a helper/for testing.  It does appear in the rubydocs when I google for it.  How do we do deprecations?

File: lib/chef/knife/core/subcommand_loader.rb (hunk 5 above)
Comment (ksubrama) [inline lib/chef/knife/core/subcommand_loader.rb]: Do folks subclass this a lot?  I can't see @env being used anywhere except to get HOME during the plugin search.  Even then, it's used inconsistently because ENV is used when looking for the manifest instead.

File: lib/chef/util/path_helper.rb (hunk 6 above)
Comment (ksubrama) [inline lib/chef/util/path_helper.rb]: I couldn't initially find a way to phrase the requirement to not have duplicates directly in a select (I'd need to refer to the set of things admitted so far) but now I just found uniq.  I can split this up into a map, filter and then uniq.

**Comment by btm** [comment]
@ksubrama could you squash some of these commits?
@chef/client-core review?

File: lib/chef/config.rb (hunk 4 above)
Comment (btm) [inline lib/chef/config.rb]: There's a complex framework that we used for deprecating some methods for Chef 12 that you can see in ```lib/chef/mixin/deprecation.rb``` but the simple thing is ```Chef::Log.deprecation("blah blah blah is blah because deprecated blah")```.

File: lib/chef/knife/core/subcommand_loader.rb (hunk 5 above)
Comment (btm) [inline lib/chef/knife/core/subcommand_loader.rb]: it's impossible to know if folks are using that argument really. Looking back at 9239ff893ea5b36db03ab53489376dcbd9536ecd, I don't see that it was ever really used, maybe @danielsdeleo remembers more.

I'd consider something like

```
def initialize(chef_config_dir, env=nil)
  if env.nil?
    env=ENV
  else
    Chef::Log.deprecation("The env argument to Chef::Knife::SubcommandLoader is deprecated, please file an issue at https://github.com/chef/chef/issues if you're using it.")
  end
end
```

Comment (danielsdeleo) [inline lib/chef/knife/core/subcommand_loader.rb]: That was mostly likely just for dependency injection in the tests. Looking around GitHub, I don't see it being used outside of Chef a lot, just copied into some vendored Chef+Ruby as a git repo thing: https://github.com/search?l=ruby&q=%27Chef%3A%3AKnife%3A%3ASubcommandLoader%27&ref=searchresults&type=Code&utf8=✓ (filter out HTML results).

**Comment by ksubrama** [comment]
Squashed.  I left pointers on the deprecation warnings on how to fix thing in case someone else was injecting stuff in their own tests.

**Comment by smurawski** [comment]
@chef/maintainers  Code review?

File: lib/chef/config.rb [hunk 10]
```diff
@@ -571,11 +571,12 @@ def self.env
     end
 
     def self.windows_home_path
-      env['SYSTEMDRIVE'] + env['HOMEPATH'] if env['SYSTEMDRIVE'] && env['HOMEPATH']
+      Chef::Log.deprecation("Chef::Config.windows_homw_path is now deprecated.  Please file an issue at https://github.com/chef/chef/issues if you're using it.  Consider using Chef::Util::PathHelper.home instead.")
```
Comment (danielsdeleo) [inline lib/chef/config.rb]: typo: `windows_homw_path`

Comment (danielsdeleo) [inline lib/chef/config.rb]: Also, why "Please file an issue at https://github.com/chef/chef/issues if you're using it." ? Seems like we either deprecate this or keep it around as a delegate method and don't deprecate it.

File: lib/chef/knife/core/subcommand_loader.rb [hunk 11]
```diff
@@ -28,9 +28,15 @@ class SubcommandLoader
...
-        @chef_config_dir, @env = chef_config_dir, env
+      def initialize(chef_config_dir, env=nil)
+        @chef_config_dir = chef_config_dir
         @forced_activate = {}
+
+        # Deprecated and un-used instance variable.
+        @env = env
+        unless env.nil?
+          Chef::Log.deprecation("The env argument to Chef::Knife::SubcommandLoader is deprecated.  Please file an issue at https://github.com/chef/chef/issues if you're using it.  If you are using env to inject/mock HOME, consider mocking Chef::Util::PathHelper.home instead.")
```
Comment (danielsdeleo) [inline lib/chef/knife/core/subcommand_loader.rb]: Same question, if we want to deprecate this, let's do it.

**Comment by tyler-ball** [comment]
Other than the deprecation comments, :+1:

**Comment by danielsdeleo** [comment]
Oops, forgot the official :+1: the deprecation stuff isn't a big deal, but I'm just not sure how you see it playing out. What would happen if we do get a issue filed?

**Comment by ksubrama** [comment]
Hey, I just got sidetracked on another issue yesterday.  I'll fix the deprecation messages to just tell people what to do instead of filing an issue.
