### PR TITLE
Lcg/fix multipackage

### LINKED ISSUE #2914: Multipackage apt installs containing virtual packages are broken
On Ubuntu 14.10:

`package [ "libxslt-dev" ]` 

is broken.

There's a bug here where `package` (an array) is used where `pkg` (the individual package) should have been used:

https://github.com/chef/chef/blob/master/lib/chef/provider/package/apt.rb#L78

After fixing that, it still blows up:

```
1) Mixlib::ShellOut::ShellCommandFailed -  multipackage_install[collected packages] (sk_role_base::packages line 12) had an error: Mixlib::ShellOut::ShellCommandFailed: apt_package[collected packages] (/var/chef/cache/cookbooks/multipackage/providers/install.rb line 8) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '2'
---- Begin output of apt-get -q -y install libxslt-dev=(none) ----
STDOUT:
STDERR: sh: 1: Syntax error: "(" unexpected
---- End output of apt-get -q -y install libxslt-dev=(none) ----
Ran apt-get -q -y install libxslt-dev=(none) returned 2
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.0.0/lib/mixlib/shellout.rb:267:in `invalid!'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.0.0/lib/mixlib/shellout.rb:254:in `error!'
/opt/chef/embedded/apps/chef/lib/chef/mixin/shell_out.rb:56:in `shell_out!'
/opt/chef/embedded/apps/chef/lib/chef/provider/package/apt.rb:179:in `run_noninteractive'
/opt/chef/embedded/apps/chef/lib/chef/provider/package/apt.rb:133:in `install_package'
/opt/chef/embedded/apps/chef/lib/chef/provider/package.rb:84:in `block in action_install'
/opt/chef/embedded/apps/chef/lib/chef/mixin/why_run.rb:52:in `call'
/opt/chef/embedded/apps/chef/lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/chef/embedded/apps/chef/lib/chef/provider.rb:180:in `converge_by'
/opt/chef/embedded/apps/chef/lib/chef/provider/package.rb:83:in `action_install'
/opt/chef/embedded/apps/chef/lib/chef/provider.rb:145:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/resource.rb:561:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
/opt/chef/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:61:in `recipe_eval_with_update_check'
/opt/chef/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:45:in `block in action'
/opt/chef/embedded/apps/chef/lib/chef/provider.rb:149:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/resource.rb:561:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:331:in `block in converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:326:in `catch'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:326:in `converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:345:in `converge_and_save'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:448:in `run'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:253:in `run_with_graceful_exit_option'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:230:in `block in run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:213:in `run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:365:in `run_application'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
/opt/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:40:in `load'
/usr/bin/chef-client:40:in `<main>'

Chef Client failed. 0 resources updated in 34.496115857 seconds
```

relevant section of the debug code showing where it goes wrong:

```
[2015-02-14T09:34:29-08:00] DEBUG: apt_package[collected packages] candidate version is 2.9.1+dfsg1-3ubuntu4.4
libxslt-dev:
  Installed: (none)
  Candidate: (none)
  Version table:
[2015-02-14T09:34:29-08:00] DEBUG: apt_package[collected packages] current version is nil
Package: libxslt-dev
Versions:

Reverse Depends:
  libabiword-3.0-dev,libxslt-dev
  ruby-build,libxslt-dev
  libabiword-3.0-dev,libxslt-dev
Dependencies:
Provides:
Reverse Provides:
libxslt1-dev 1.1.28-2build1
[2015-02-14T09:34:29-08:00] INFO: apt_package[collected packages] is a virtual package, actually acting on package[libxslt1-dev]
libxslt1-dev:
  Installed: 1.1.28-2build1
  Candidate: 1.1.28-2build1
  Version table:
 *** 1.1.28-2build1 0
        500 http://us.archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
```

Its getting '(none)' from the virtual package not the real package, and is thinking it isn't installed when libxslt1-dev really is installed.

### PR DESCRIPTION
**Pull request by lamont-granquist**
Change a lot of the arrays in check_package_state to hashes indexed by the package name.   There was recursion in check_package_state when dealing with virtual packages which was being handled incorrectly and winding up adding the results from interrogating the virtual packages into the arrays that check_package_state builds which was throwing off the indexes in those arrays.

Its still a bit ugly, but this is a bit clearer and feels like minimum viable patch to fix the brokenness before shipping.  Need to do some remaining cleanup for 12.2.0

fixes #2914

### CODE REVIEW

**Comment by jaymzh** [comment]
Sorry, I've been out of the country and off the grid (I saw in my massive backlog of email some bugs about this). Tomorrow's my only day at work before leaving for SCALE, I'll try to review this before I leave.

**Comment by lamont-granquist** [comment]
This is still incomplete, needs specs added for the cases that I fixed.

**Comment by jdmundrawala** [comment]
spec in https://github.com/chef/chef/pull/2929

File: lib/chef/provider/package/apt.rb [hunk 1]
```diff
@@ -138,20 +149,12 @@ def upgrade_package(name, version)
         end
 
         def remove_package(name, version)
-          if name.is_a?(Array)
-            package_name = name.join(' ')
-          else
-            package_name = name
-          end
+          package_name = [ name ].flatten.join(' ')
```
Comment (jdmundrawala) [inline lib/chef/provider/package/apt.rb]: This is repeated a bunch of times, might be nice to factor it out

File: lib/chef/provider/package/apt.rb [hunk 2]
```diff
@@ -50,86 +56,91 @@ def default_release_options
...
-                  raise Chef::Exceptions::Package, "#{@new_resource.package_name} has no candidate in the apt-cache" if num_providers == 0
-                  # apt will only install a virtual package if there is a single providing package
-                  raise Chef::Exceptions::Package, "#{@new_resource.package_name} is a virtual package provided by #{num_providers} packages, you must explicitly select one to install" if num_providers > 1
-                  # Check if the package providing this virtual package is installed
-                  Chef::Log.info("#{@new_resource} is a virtual package, actually acting on package[#{providers.keys.first}]")
-                  installed = check_package_state(providers.keys.first)
-                else
-                  Chef::Log.debug("#{@new_resource} candidate version is #{$1}")
+        def check_package_state(pkg)
+          is_virtual_package = false
```
Comment (jdmundrawala) [inline lib/chef/provider/package/apt.rb]: style comment:
not a fan of the shadowing...also, below you used `installed` instead of `is_installed`

File: lib/chef/provider/package/apt.rb [hunk 3]
```diff
@@ -50,86 +56,91 @@ def default_release_options
...
-            end
           end
-          @candidate_version = final_candidate_version
-          @current_resource.version(final_installed_version)
-          @is_virtual_package = final_virtual
- 
-          return final_installed.is_a?(Array) ? final_installed.any? : final_installed
+
+          return {
+            installed_version:   installed_version,
```
Comment (jaymzh) [inline lib/chef/provider/package/apt.rb]: I have a special hatred for this hash syntax in ruby.

File: lib/chef/provider/package/apt.rb [hunk 4]
```diff
@@ -50,86 +56,91 @@ def default_release_options
...
+            @candidate_version = candidate_version[package]
+            @current_resource.version(installed_version[package])
           end
+        end
+
+        def install_package(name, version)
+          name_array = [ name ].flatten
+          version_array = [ version ].flatten
+          package_name = name_array.zip(version_array).map do |n, v|
+            is_virtual_package[n] ? n : "#{n}=#{v}"
```
Comment (jaymzh) [inline lib/chef/provider/package/apt.rb]: do you mean `@is_virtual_package` here?

Comment (lamont-granquist) [inline lib/chef/provider/package/apt.rb]: nope, its declared an accessor, better to drop the `@`

i was tempted to rage fix and drop all the `@` signs everywhere on accessors (all the `@new_resource` and `@current_resource` stuff makes my eyes bleed now), but want to keep this mostly confined to fixing the bug and not a style overhaul.

File: lib/chef/provider/package/apt.rb (hunk 3 above)
Comment (lamont-granquist) [inline lib/chef/provider/package/apt.rb]: I :heart: it so much.

I feel like I'm giving the middle finger to ruby 1.8.7 every time I use it.  It fills me with great joy =)

File: lib/chef/provider/package/apt.rb (hunk 1 above)
Comment (lamont-granquist) [inline lib/chef/provider/package/apt.rb]: If it was still written the way that I replaced, I'd agree.  As it is, its clear and pretty concise and makes the implementation really obvious.

I want to do a style rage-fix cleanup after 12.1.0 ships, anyway, though, and want to step back and see if there might not be a better way to do this (e.g. maybe the subclass should expose remove_package_array() instead of remove_package() and the superclass will be responsible for doing `respond_to?(:remove_package_array)` and coercing the argument into an array, then this line goes away -- all this array-or-scaler argument stuff is messy and I'd like it more contained).

File: lib/chef/provider/package/apt.rb (hunk 3 above)
Comment (jaymzh) [inline lib/chef/provider/package/apt.rb]: It's super buggy, there's a ton of things you can't do it with it, it just sucks. I would be happy it I could stop using the other one, but I can't, so why would I want to use one syntax sometimes, and another one other times? So. Much. Hate.

File: lib/chef/provider/package/apt.rb (hunk 4 above)
Comment (jaymzh) [inline lib/chef/provider/package/apt.rb]: ah, I missed the accessor

**Comment by lamont-granquist** [comment]
commits squashed and rebased on master, will fail travis due to ohai 8.1.0 bug

**Comment by jaymzh** [comment]
:+1:
