### PR TITLE
[data-collector] improved output_locations validation & bug fixes

### LINKED ISSUE #10391: [data-collector] FATAL: NoMethodError: undefined method `start_time' for nil:NilClass
## Description

If any error in config occurs in data collector config options seems `run_context` being assigned with nil that leads to  `FATAL: NoMethodError: undefined method `start_time' for nil:NilClass` accessing `start_time` on nil `run_context`.

## Chef Version

local mode latest master & Chef Infra Client: 16.4.41

## Platform Version

Ubuntu 18.04

## Replication Case

Put some deliberate errors in client.rb config option is being accessed in `start_run` context.

```
data_collector.output_locations = ["~/abc.txt"] # Valid data_collector.output_locations = { files: ["~/abc.txt"]}
```

## Client Output

```
Running handlers:
[2020-09-07T22:30:05+05:30] ERROR: Running exception handlers
Running handlers complete
[2020-09-07T22:30:05+05:30] ERROR: Exception handlers complete
Chef Infra Client failed. 0 resources updated in 02 seconds
[2020-09-07T22:30:05+05:30] FATAL: NoMethodError: undefined method `start_time' for nil:NilClass
```

### PR DESCRIPTION
**Pull request by vsingh-msys**
## Description

- Fix invalid output_locations raise start_time error.
- Improve validate_output_locations!

## Related Issue

Fixes #10391 & #10392 

Automate Epic: https://github.com/chef/automate/issues/4141
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

Signed-off-by: Vivek Singh <vivek.singh@msystechnologies.com>

### CODE REVIEW

File: lib/chef/data_collector.rb [hunk 1]
```diff
@@ -115,9 +117,6 @@ def action_collection_registration(action_collection)
       # (see EventDispatch::Base#run_started)
       #
       def run_started(run_status)
-        Chef::DataCollector::ConfigValidation.validate_server_url!
-        Chef::DataCollector::ConfigValidation.validate_output_locations!
-
```
Comment (vsingh-msys) [inline lib/chef/data_collector.rb:120]: Moved these validations from here and added into `run_start` so that it can pre-validate the when run going to start. As the event sequence defined `run_start` called at step 4 and `run_started` called at step 9 https://github.com/chef/chef/blob/master/docs/dev/design_documents/data_collector.md#relevant-event-sequence

File: lib/chef/data_collector.rb [hunk 2]
```diff
@@ -210,10 +209,10 @@ def send_to_data_collector(message)
       # @param message [Hash] message to send
       #
       def send_to_output_locations(message)
-        return unless Chef::Config[:data_collector][:output_locations]
+        Chef::DataCollector::ConfigValidation.validate_output_locations!
 
         Chef::Config[:data_collector][:output_locations].each do |type, locations|
-          locations.each do |location|
+          Array(locations).each do |location|
```
Comment (vsingh-msys) [inline lib/chef/data_collector.rb:215]: Allow locations as a single value String or Array for more flexible options value.

File: lib/chef/data_collector.rb [hunk 3]
```diff
@@ -226,7 +225,7 @@ def send_to_output_locations(message)
       # @param message [Hash] the message to render as JSON
       #
       def send_to_file_location(file_name, message)
-        File.open(file_name, "a") do |fh|
+        File.open(File.expand_path(file_name), "a") do |fh|
```
Comment (vsingh-msys) [inline lib/chef/data_collector.rb:228]: File.open accepts only an absolute file path. Consider the relative's path to avoids error.

File: lib/chef/data_collector/run_end_message.rb [hunk 4]
```diff
@@ -60,8 +60,8 @@ def construct_message(data_collector, status)
             "cookbooks" => ( node && node["cookbooks"] ) || {},
             "policy_name" => node&.policy_name,
             "policy_group" => node&.policy_group,
-            "start_time" => run_status.start_time.utc.iso8601,
-            "end_time" => run_status.end_time.utc.iso8601,
+            "start_time" => run_status&.start_time&.utc&.iso8601,
+            "end_time" => run_status&.end_time&.utc&.iso8601,
```
Comment (vsingh-msys) [inline lib/chef/data_collector/run_end_message.rb:64]: Added safe navigator operator to fix `FATAL: NoMethodError: undefined method `start_time' for nil:NilClass` accessing `start_time` on nil `run_context`.

File: lib/chef/data_collector.rb (hunk 1 above)
Comment (vsingh-msys) [reply lib/chef/data_collector.rb]: Reverted this as integrations specs are failing due to in `run_start` we have not finalized which mode would be enabled so every time are validating `validate_server_url!`

File: docs/dev/design_documents/data_collector.md [hunk 5]
```diff
@@ -507,11 +507,12 @@ Chef::Config[:data_collector][:token] = "mytoken"
 
 This works for chef-clients, which are configured to hit a Chef server, but use a custom non-Chef-Automate endpoint for reporting, or for chef-solo/zero users.
 
-XXX: There is also the `Chef::Config[:data_collector][:output_locations] = { uri: [ "https://chef.acme.local/myendpoint.html" ] }` method, which will behave differently, particularly on non-chef-solo use cases. 
+XXX: There is also the `Chef::Config[:data_collector][:output_locations] = { urls: [ "https://chef.acme.local/myendpoint.html" ] }` method, which will behave differently, particularly on non-chef-solo use cases.
```
Comment (lamont-granquist) [inline docs/dev/design_documents/data_collector.md:510]: what that just a doc bug or is this a breaking change?

Comment (vsingh-msys) [reply docs/dev/design_documents/data_collector.md:510]: Yeah, it just a doc bug.

Comment (lamont-granquist) [reply docs/dev/design_documents/data_collector.md:510]: 👍

File: lib/chef/data_collector/config_validation.rb [hunk 6]
```diff
@@ -105,7 +110,7 @@ def should_be_enabled?
 
         # validate an output_location file
         def validate_file!(file)
-          open(file, "a") {}
+          File.open(File.expand_path(file), "a") {}
```
Comment (phiggins) [inline lib/chef/data_collector/config_validation.rb:113]: This seems like the wrong way to test this. Do you know if `File.open` will raise the same exceptions that `open` does? Using `File.exist?` and `File.writable?` would probably be a little better, but I'm not sure what exceptions the last case is trying to catch.

File: lib/chef/data_collector/config_validation.rb [hunk 7]
```diff
@@ -125,6 +130,17 @@ def validate_url!(url)
...
+        #
+        # @param hash [Hash] the hash contains data collector output_locations.
+        # @param keys [Array] the multiple keys as arguments array.
+        # @return [Boolean] true if the hash contains either of keys or both.
+        #
+        def valid_hash_with_keys?(hash, *keys)
+          return false if hash.empty? || !hash.is_a?(Hash)
+
+          keys.any? { |k| hash.key?(k) }
+        end
```
Comment (phiggins) [inline lib/chef/data_collector/config_validation.rb:143]:
```suggestion
        def valid_hash_with_keys?(hash, *keys)
          hash.is_a?(Hash) && keys.any? { |k| hash.key?(k) }
        end
```

File: lib/chef/data_collector/config_validation.rb [hunk 8]
```diff
@@ -125,6 +130,17 @@ def validate_url!(url)
             "Chef::Config[:data_collector][:output_locations][:urls] contains the url #{url} which is not valid."
         end
 
+        # Validate a non-empty hash that includes either of keys of both.
+        #
+        # @param hash [Hash] the hash contains data collector output_locations.
+        # @param keys [Array] the multiple keys as arguments array.
+        # @return [Boolean] true if the hash contains either of keys or both.
+        #
```
Comment (phiggins) [inline lib/chef/data_collector/config_validation.rb:138]:
```suggestion
        # Validate the hash contains at least one of the given keys.
        #
        # @param hash [Hash] the hash to be validated.
        # @param keys [Array] an array of keys to check existence of in the hash.
        # @return [Boolean] true if the hash contains any of the given keys.
        #
```

Comment (vsingh-msys) [reply lib/chef/data_collector/config_validation.rb:138]: Thanks! @phiggins

**Review by phiggins — APPROVED** [review]
Definitely an improvement. Nice work 👍

File: lib/chef/data_collector/config_validation.rb (hunk 6 above)
Comment (vsingh-msys) [reply lib/chef/data_collector/config_validation.rb:113]: @phiggins AFAIK `File.open` raises the same exceptions and `Kernel.open` also works for process and subprocess to open.

I would prefer to use `Chef::Config.path_accessible?` to check the file is writable of not.

I think the last case for sanity purposes only.

Comment (lamont-granquist) [reply lib/chef/data_collector/config_validation.rb]: Yeah this is very hacky code, and I think its just working around windows cases where `File.exist?` / `File.writable?` checks may not be sufficient, so it just tries to open-and-rescue.  I had questions around if it was really necessary and if the cases had been seen in reality and find the whole thing a bit dubious, but didn't know enough to definitively make the call to change this approach.  I kind of left it all alone.

**Comment by tas50** [comment]
@vsingh-msys Can you take a look at these windows unit tests failures: https://buildkite.com/chef-oss/chef-chef-master-verify/builds/6137
