### PR TITLE
Fix dnf_package version and arch property support and idempotency

### LINKED ISSUE #9763: dnf_package (and most likely yum_package) issues with version property
These all work correctly:

```
dnf_package "zabbix-agent-4.0.15"
dnf_package "zabbix-agent-4.0*"
dnf_package "zabbix-agent-4.0.15-1.fc31"
dnf_package "zabbix-agent-4.0*-1.fc31"
dnf_package "zabbix-agent-4.0.15-*"
dnf_package "zabbix-agent-4.0*-*"
dnf_package "zabbix-agent-1:4.0.15"
dnf_package "zabbix-agent-1:4.0.*"
dnf_package "zabbix-agent-1:4.0.15-1.fc31"
dnf_package "zabbix-agent-1:4.0*-1.fc31"
dnf_package "zabbix-agent-*:4.0.15-*"
dnf_package "zabbix-agent-*:4.0*-*"
```

These do all do not work (but correctly so):

```
#dnf_package "zabbix-agent-4.0"
#dnf_package "zabbix-agent-4.0.15-1"
#dnf_package "zabbix-agent-1:4.0.15-1"
#dnf_package "zabbix-agent-*:4.0.15-1"
#dnf_package "zabbix-agent-*:4.0.15-1.fc31"
```

The CLI does not support those five either:

```
[root@default-fedora-latest vagrant]# dnf install zabbix-agent-4.0
Last metadata expiration check: 0:20:31 ago on Wed 29 Apr 2020 01:09:14 AM UTC.
No match for argument: zabbix-agent-4.0
Error: Unable to find a match: zabbix-agent-4.0
[root@default-fedora-latest vagrant]# dnf install zabbix-agent-4.0.15-1
Last metadata expiration check: 0:20:37 ago on Wed 29 Apr 2020 01:09:14 AM UTC.
No match for argument: zabbix-agent-4.0.15-1
Error: Unable to find a match: zabbix-agent-4.0.15-1
[root@default-fedora-latest vagrant]# dnf install zabbix-agent-1:4.0.15-1
Last metadata expiration check: 0:20:44 ago on Wed 29 Apr 2020 01:09:14 AM UTC.
No match for argument: zabbix-agent-1:4.0.15-1
Error: Unable to find a match: zabbix-agent-1:4.0.15-1
[root@default-fedora-latest vagrant]# dnf install 'zabbix-agent-*:4.0.15-1'
Last metadata expiration check: 0:21:06 ago on Wed 29 Apr 2020 01:09:14 AM UTC.
No match for argument: zabbix-agent-*:4.0.15-1
Error: Unable to find a match: zabbix-agent-*:4.0.15-1
[root@default-fedora-latest vagrant]# dnf install 'zabbix-agent-*:4.0.15-1.fc31'
Last metadata expiration check: 0:21:16 ago on Wed 29 Apr 2020 01:09:14 AM UTC.
No match for argument: zabbix-agent-*:4.0.15-1.fc31
Error: Unable to find a match: zabbix-agent-*:4.0.15-1.fc31
```

When used as a version property the only use case which works entirely correctly is the fully specified case:

```
dnf_package "zabbix-agent" do
  version "1:4.0.15-1.fc31"
end
```

When used as a version property the following use case crash hard:

```
dnf_package "zabbix-agent" do
  version "*:4.0.15-*"
end

dnf_package "zabbix-agent" do
  version "-*:4.0*-*"
end
```

The exception is probably fixable and is:

```
[2020-04-29T01:35:31+00:00] FATAL: RuntimeError: dnf_package[zabbix-agent] ((chef-apply cookbook)::(chef-apply recipe) line 7) had an error: RuntimeError: dnf-helper.py had stderr/stdout output:

Traceback (most recent call last):
  File "/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/provider/package/dnf/dnf_helper.py", line 166, in <module>
    query(command)
  File "/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/provider/package/dnf/dnf_helper.py", line 101, in query
    q = q.filterm(epoch=int(command['epoch']))
ValueError: invalid literal for int() with base 10: '-*'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/provider/package/dnf/dnf_helper.py", line 173, in <module>
    base.closeRpmDB()
AttributeError: 'Base' object has no attribute 'closeRpmDB'
```

When used as a version property the following uses cases appear to work but are not idempotent:

```

dnf_package "zabbix-agent" do
  version "4.0.15"
end

dnf_package "zabbix-agent" do
  version "4.0*"
end

dnf_package "zabbix-agent" do
  version "4.0.15-1.fc31"
end

dnf_package "zabbix-agent" do
  version "4.0*-1.fc31"
end

dnf_package "zabbix-agent" do
  version "4.0.15-*"
end

dnf_package "zabbix-agent" do
  version "4.0*-*"
end

dnf_package "zabbix-agent" do
  version "1:4.0.15"
end

dnf_package "zabbix-agent" do
  version "1:4.0.*"
end

dnf_package "zabbix-agent" do
  version "1:4.0*-1.fc31"
end
```

Tested On:  Fedora release 31 (Thirty One)

Client version: Chef Infra Client: 16.0.257

Aha! Link: https://chef.aha.io/features/SH-111

### PR DESCRIPTION
**Pull request by lamont-granquist**
This does two things:

1.  Fixes the filtering by name, version + arch.  This introduces one incompatibility which is that putting the arch in the version property was supported at one point in time with a test that I committed which doesn't seem to be used anywhere.  But we also now should correctly support mixing and matching the name with versions and arches in them combined with a version property and/or arch property.  Which is a bit crazy but it supports doing `package "openssl.i686"` with a version property.  It should now behave the same using either the property or putting the version and arch into the name.

2.  It changes the meaning of the "current_version" in the superclass (or confusingly the "installed_version" in the subclass) so that if a version of the package is installed, which does not match the requested version+arch filtering, the value is set to nil.  This is done so that the superclass can check current_version.nil? in order to check to see if a "good" package is installed or not.  This changes the semantics of that variable where previously it reported whatever version was installed.  The subclass_directive that is introduced switches between those behaviors.  The result is 2 fewer comparison operations that the superclass asks of the subclass which also speeds up execution.

This fixes many edge conditions around idempotency, along with differences in the supported APIs and idemopotency behavior between specifying the version constraints in the name and specifying the version constraints in the version property of the resource.

There's an unrelated fix to exception handling and crashes.

closes  #9763

Aha! Link: https://chef.aha.io/features/SH-120

### CODE REVIEW

**Comment by breisig** [comment]
Can we get this merged.

**Comment by lamont-granquist** [comment]
the "upgrade" tests include downgrades

File: lib/chef/provider/package.rb [hunk 1]
```diff
@@ -414,19 +433,19 @@ def target_version_array
...
-                  logger.trace("#{new_resource} #{package_name} #{new_version} is already installed -- you are equality pinning with an :upgrade action, this may be deprecated in the future")
-                  target_version_array.push(nil)
-                elsif version_equals?(current_version, candidate_version)
-                  logger.trace("#{new_resource} #{package_name} #{candidate_version} is already installed")
+                if current_version.nil?
+                  logger.trace("#{new_resource} has no existing installed version. Installing install #{candidate_version}")
+                  target_version_array.push(candidate_version)
+                elsif version_equals?(current_version, new_version)
+                  # this is a short-circuit to avoid needing to (expensively) query the candidate_version which must come later
+                  logger.trace("#{new_resource} #{package_name} #{new_version} is already installed")
```
Comment (jaymzh) [inline lib/chef/provider/package.rb:441]: I would put the warning back. pinning in :upgrade is weird and we still may kill it

File: lib/chef/provider/package.rb [hunk 2]
```diff
@@ -414,19 +433,19 @@ def target_version_array
             each_package do |package_name, new_version, current_version, candidate_version|
               case action
               when :upgrade
-                if version_equals?(current_version, new_version)
-                  # this is an odd use case
-                  logger.trace("#{new_resource} #{package_name} #{new_version} is already installed -- you are equality pinning with an :upgrade action, this may be deprecated in the future")
-                  target_version_array.push(nil)
-                elsif version_equals?(current_version, candidate_version)
-                  logger.trace("#{new_resource} #{package_name} #{candidate_version} is already installed")
+                if current_version.nil?
```
Comment (jaymzh) [inline lib/chef/provider/package.rb:436]: it's entirely unclear here how it's possible for current_version != new_version but current_version != candidate_version. I mean *I* get it because I've been talking to you about those stuff for weeks, but I would add a TON of comments here for future-Lamont and future-Phil.

File: lib/chef/provider/package/dnf/dnf_helper.py [hunk 3]
```diff
@@ -98,14 +98,24 @@ def query(command):
         q = q.available()
 
     if 'epoch' in command:
-        q = q.filterm(epoch=int(command['epoch']))
+        if not dnf.util.is_glob_pattern(command['epoch']):
```
Comment (jaymzh) [inline lib/chef/provider/package/dnf/dnf_helper.py:101]: why drop this if it's a glob? Is there not a epoch__glob filter?

File: spec/functional/resource/dnf_package_spec.rb [hunk 4]
```diff
@@ -128,13 +127,114 @@ def pkg_arch
...
+          expect(shell_out("rpm -q --queryformat '%{NAME}-%{VERSION}-%{RELEASE}.%{ARCH}\n' chef_rpm").stdout.chomp).to match("^chef_rpm-1.2-1.#{pkg_arch}$")
+        end
+      end
+
+      %w{1.2 1.2-1 1.2-* 0:1.2 0:1.2-1 *:1.2-*}.each do |vstring|
+        it "is idempotent when #{vstring} is in the version property on upgrade and it doesn't match the candidate version" do
+          preinstall("chef_rpm-1.2-1.#{pkg_arch}.rpm")
+          dnf_package.package_name("chef_rpm")
+          dnf_package.version(vstring)
+          dnf_package.run_action(:upgrade)
```
Comment (jaymzh) [inline spec/functional/resource/dnf_package_spec.rb:209]: this is a pretty big change... you're now saying that:
```
package 'foo' do
  version '1.2'
  action :install # or :upgrade
end
```

will work and install the latest-release of 1.2. That needs to be called out BIG TIME in the release notes. Before that would break.

File: spec/functional/resource/dnf_package_spec.rb [hunk 5]
```diff
@@ -715,32 +914,104 @@ def pkg_arch
...
+        dnf_package.version("1.10-1")
         dnf_package.run_action(:upgrade)
         expect(dnf_package.updated_by_last_action?).to be true
         expect(shell_out("rpm -q --queryformat '%{NAME}-%{VERSION}-%{RELEASE}.%{ARCH}\n' chef_rpm").stdout.chomp).to match("^chef_rpm-1.10-1.#{pkg_arch}$")
+        dnf_package.run_action(:upgrade)
+        expect(dnf_package.updated_by_last_action?).to be false
       end
 
-      it "with a prco equality pin in the name it upgrades a prior package" do
+      it "with a full version pin in the name it downgrdes the package" do
```
Comment (jaymzh) [inline spec/functional/resource/dnf_package_spec.rb:934]:
```suggestion
      it "with a full version pin in the name it downgrades the package" do
```

File: spec/functional/resource/dnf_package_spec.rb [hunk 6]
```diff
@@ -715,32 +914,104 @@ def pkg_arch
...
+        dnf_package.package_name("chef_rpm")
+        dnf_package.version("1.10")
+        dnf_package.run_action(:upgrade)
+        expect(dnf_package.updated_by_last_action?).to be true
+        expect(shell_out("rpm -q --queryformat '%{NAME}-%{VERSION}-%{RELEASE}.%{ARCH}\n' chef_rpm").stdout.chomp).to match("^chef_rpm-1.10-1.#{pkg_arch}$")
+        dnf_package.run_action(:upgrade)
+        expect(dnf_package.updated_by_last_action?).to be false
+      end
+
+      it "with a partial (no release) version pin in the name it downgrdes the package" do
```
Comment (jaymzh) [inline spec/functional/resource/dnf_package_spec.rb:956]:
```suggestion
      it "with a partial (no release) version pin in the name it downgrades the package" do
```

File: spec/functional/resource/dnf_package_spec.rb [hunk 7]
```diff
@@ -715,32 +914,104 @@ def pkg_arch
...
+        preinstall("chef_rpm-1.2-1.#{pkg_arch}.rpm")
+        dnf_package.package_name("chef_rpm-1.10-1")
+        dnf_package.run_action(:upgrade)
+        expect(dnf_package.updated_by_last_action?).to be true
+        expect(shell_out("rpm -q --queryformat '%{NAME}-%{VERSION}-%{RELEASE}.%{ARCH}\n' chef_rpm").stdout.chomp).to match("^chef_rpm-1.10-1.#{pkg_arch}$")
+        dnf_package.run_action(:upgrade)
+        expect(dnf_package.updated_by_last_action?).to be false
+      end
+
+      it "with a full version pin in the name it downgrdes the package" do
```
Comment (jaymzh) [inline spec/functional/resource/dnf_package_spec.rb:977]:
```suggestion
      it "with a full version pin in the name it downgrades the package" do
```

File: spec/functional/resource/dnf_package_spec.rb [hunk 8]
```diff
@@ -715,32 +914,104 @@ def pkg_arch
...
+        dnf_package.package_name("chef_rpm-1.10")
         dnf_package.run_action(:upgrade)
         expect(dnf_package.updated_by_last_action?).to be true
         expect(shell_out("rpm -q --queryformat '%{NAME}-%{VERSION}-%{RELEASE}.%{ARCH}\n' chef_rpm").stdout.chomp).to match("^chef_rpm-1.10-1.#{pkg_arch}$")
+        dnf_package.run_action(:upgrade)
+        expect(dnf_package.updated_by_last_action?).to be false
       end
 
-      it "with an equality pin in the name it downgrades a later package" do
+      it "with a partial (no release) version pin in the name it downgrdes the package" do
```
Comment (jaymzh) [inline spec/functional/resource/dnf_package_spec.rb:997]:
```suggestion
      it "with a partial (no release) version pin in the name it downgrades the package" do
```

File: spec/functional/resource/dnf_package_spec.rb [hunk 9]
```diff
@@ -715,32 +914,104 @@ def pkg_arch
...
         dnf_package.run_action(:upgrade)
         expect(dnf_package.updated_by_last_action?).to be true
         expect(shell_out("rpm -q --queryformat '%{NAME}-%{VERSION}-%{RELEASE}.%{ARCH}\n' chef_rpm").stdout.chomp).to match("^chef_rpm-1.2-1.#{pkg_arch}$")
+        dnf_package.run_action(:upgrade)
+        expect(dnf_package.updated_by_last_action?).to be false
+      end
+
+      it "with a prco equality pin in the name it upgrades a prior package" do
+        preinstall("chef_rpm-1.2-1.#{pkg_arch}.rpm")
+        dnf_package.package_name("chef_rpm = 1.10")
```
Comment (jaymzh) [inline spec/functional/resource/dnf_package_spec.rb:1009]: wat? That's a syntax?

**Review by jaymzh — COMMENTED** [review]
seems generally OK.
This does not fix the open bug with multipackage, but I don't think you intended to.

File: lib/chef/provider/package/dnf/dnf_helper.py (hunk 3 above)
Comment (lamont-granquist) [reply lib/chef/provider/package/dnf/dnf_helper.py:101]: no if its a glob, it is '*' so it matches anything so you don't filter.

i beat my head against that one for a bit.

i suppose i could try a comment.

File: spec/functional/resource/dnf_package_spec.rb (hunk 4 above)
Comment (lamont-granquist) [reply spec/functional/resource/dnf_package_spec.rb:209]: that's the bug that is being fixed.

File: spec/functional/resource/dnf_package_spec.rb (hunk 9 above)
Comment (lamont-granquist) [reply spec/functional/resource/dnf_package_spec.rb:1009]: yep that's not new, this is just rearrangement from existing tests.  works the same way on the commandline

Comment (lamont-granquist) [reply spec/functional/resource/dnf_package_spec.rb:1009]: it also supports any `provides` lines in the RPMs, with that kind of version string syntax.

File: lib/chef/provider/package.rb (hunk 1 above)
Comment (lamont-granquist) [reply lib/chef/provider/package.rb:441]: even if you delete this line because of the way that the candidate and installed versions are both filtered by the new_resource.version and/or the version constraints in the package_name it still works.  that line (at least for the DNF package provider now and soon the yum provider) is just a performance optimization now if you equality match (to avoid querying the candidate_version, which can be expensive in some of the subclasses).

Comment (lamont-granquist) [reply lib/chef/provider/package.rb:441]: (and we haven't deleted in that in the years that comment has been sitting there, i'm pretty confident at this point that we never will)

File: lib/chef/provider/package.rb (hunk 2 above)
Comment (lamont-granquist) [reply lib/chef/provider/package.rb:436]: candidate_version and current_version are always fully materialized EVRs (in the yum/dnf subclasses) because they come back from queries.

the new_version comes from the user and can be "1.*" or whatever.  and "1.2-1" != "1.*".  i was going to go down the road of having a `installed_version.satisfied_by?(new_version)` API that could be called in the subclass, but that looked like it was going to require a lot of python code that would duplicate internal code in the dnf library.  making it so that the installed_version was just automatically satisfied_by the new_version (or else it being nil) was vastly simpler and will be more robust and gets what we actually need.  that way if either candidate_version or installed_version is nil it either doesn't exist, or doesn't satisfy the desired constraint and either way we have to do work to fix it.

**Comment by lamont-granquist** [comment]
Note to self that I need to fix the condition when the installed_version will now be nil when the new_version doesn't match and the user will get green text about nil being upgrading/downgraded to the desired version, when the package was actually installed.

Similarly need to make sure that the "before" resource (current_resource) has the right version number for reporting.  So we need to populate it there and print that in the superclass for output to the user, while we use the installed_version in the subclass.  Existing subclasses generally set those to the same value so it shouldn't affect anything with other subclasses, they won't care.

File: lib/chef/provider/package/dnf/dnf_helper.py (hunk 3 above)
Comment (jaymzh) [reply lib/chef/provider/package/dnf/dnf_helper.py:101]: what if it's a glob that's *not* that. what if my glob is `1?` ?

File: spec/functional/resource/dnf_package_spec.rb (hunk 4 above)
Comment (jaymzh) [reply spec/functional/resource/dnf_package_spec.rb:209]: I mean... sorta? You had to be explicit before. The bug you're fixing is that specifying arch in weird places would lead to lack of idempotency.
I'm not saying this is wrong, but this is definitely gonna lead to some unexpected surprises for people.

File: lib/chef/provider/package.rb (hunk 2 above)
Comment (jaymzh) [reply lib/chef/provider/package.rb:436]: Oh I understand it. I'm just saying .... comment your damn code. :)

File: lib/chef/provider/package.rb (hunk 1 above)
Comment (jaymzh) [reply lib/chef/provider/package.rb:441]: yeah I was totally wrong. This is a valid thing to do now. You might want to upgrade to whatever the latest release of 1.2 is

File: lib/chef/provider/package.rb [hunk 10]
```diff
@@ -414,19 +433,19 @@ def target_version_array
...
+                  logger.trace("#{new_resource} has no existing installed version. Installing install #{candidate_version}")
+                  target_version_array.push(candidate_version)
+                elsif version_equals?(current_version, new_version)
```
[the remark this answers is not in the document]
Comment (epilatow) [reply lib/chef/provider/package.rb:439]: Well, I downloaded this code, monkeypatched it into our code base, ran my tests, and I'm happy to report that the tests succeeded. It seems we never tried to do the aforementioned broken comparisons because `current_version` was nil (even though there was a current version of the package installed). I think you tried to explain this earlier to me when you said:

> went a completely different direction so that the subclass can direct the superclass that the installed_version ("current_version" in the superclass) is nil if it doesn't match the version constraint.  so that value can be nil if there's a package installed but it doesn't match what the resource wants.

That said, while running chef in debug mode I am still seeing a lot of `versioncompare` calls, some with version numbers that we will parse incorrectly:
```
[2020-12-10T16:46:28-08:00] DEBUG: sending '{"action":"versioncompare","versions":["0:2020.2.41-80.0.el8_2.noarch","0:2020.2.41-80.0.el8_2.noarch"]}' to python helper
[2020-12-10T16:46:34-08:00] DEBUG: sending '{"action":"versioncompare","versions":["0:60.3-2.el8_1.x86_64","0:60.3-2.el8_1.x86_64"]}' to python helper
[2020-12-10T16:46:34-08:00] DEBUG: sending '{"action":"versioncompare","versions":["0:60.3-2.el8_1.x86_64","0:60.3-2.el8_1.x86_64"]}' to python helper
[2020-12-10T16:46:34-08:00] DEBUG: sending '{"action":"versioncompare","versions":["1:0.17-73.el8_1.1.x86_64","1:0.17-73.el8_1.1.x86_64"]}' to python helper
```

Most of these seem to be occurring with multi-package resources in the :upgrade path on line 446:
```
                 elsif version_equals?(current_version, candidate_version)
```

But in all these cases we're doing an equality comparison on identical strings, so it seems like things will work even though we're not parsing EVRAs correctly. It seems like your changes essentially eliminate all version comparisons (other than for equality comparisons for equal strings). If that's true then the dnf versioncompare code is dead, so why not remove it and update the dnf 'python_helper.rb`compare_versions()' function to assert v1 == v2 and always return 0? That'd make the code less complex and the constraints more obvious. (If that assumption is not true then it seems like there should be a way to make the version comparisons fail with the current parsing code.)

[the remark this answers is not in the document]
Comment (lamont-granquist) [reply lib/chef/provider/package.rb:439]: >  because current_version was nil (even though there was a current version of the package installed)

yep that's the point of `installed_version_satisfies_version_constraints` -- if it doesn't satisfy the version constraints then its nil, even though it is installed.

have to parse the rest of that tomorrow, but you're right that versioncompare is basically unimportant now.

File: lib/chef/provider/package/dnf/dnf_helper.py (hunk 3 above)
Comment (lamont-granquist) [reply lib/chef/provider/package/dnf/dnf_helper.py:101]: looks like that is actually legal, but i don't know how to fix that since i don't see how the underlying dnf libraries do that globbing.

so that's just going to be known broken.  i can't imagine that is an actually useful use case though.  and the dnf libaries themselves have several bugs around handling wildcards in epoch versions (see the #9763 use cases which work and which don't).
