### PR TITLE
Assume credentials supplied are still valid if they cannot be validated due to a Windows account restriction

### LINKED ISSUE #7412: windows_user with empty password is not idempotent
## Description

Chef keeps running `windows_user` with empty password even though no changes have been made.

## Chef Version

* `13.9.4`

## Platform Version

* Windows Server 2012 R2

## Replication Case

```
user 'example' do
  action :create
end
```

## Client Output

First `chef-client` execution (`DEBUG` log level):

```
[2018-06-29T15:41:35+00:00] DEBUG: Converging node karaf-mwrock-Windows2012R2
Recipe: aet::user
    * windows_user[example] action create[2018-06-29T15:41:35+00:00] INFO: Processing windows_user[example] action create (aet::user line 1)
[2018-06-29T15:41:35+00:00] INFO: Processing windows_user[example] action create (aet::user line 1)
[2018-06-29T15:41:35+00:00] DEBUG: Providers for generic windows_user resource enabled on node include: [Chef::Provider::User::Windows]
[2018-06-29T15:41:35+00:00] DEBUG: Providers for generic windows_user resource enabled on node include: [Chef::Provider::User::Windows]
[2018-06-29T15:41:35+00:00] DEBUG: Provider for action create on resource windows_user[example] is Chef::Provider::User::Windows
[2018-06-29T15:41:35+00:00] DEBUG: Provider for action create on resource windows_user[example] is Chef::Provider::User::Windows
[2018-06-29T15:41:35+00:00] DEBUG: windows_user[example] does not exist (The user name could not be found.)
[2018-06-29T15:41:35+00:00] DEBUG: windows_user[example] does not exist (The user name could not be found.)
[2018-06-29T15:41:35+00:00] INFO: windows_user[example] created
[2018-06-29T15:41:35+00:00] INFO: windows_user[example] created

    - create user example
[2018-06-29T15:41:35+00:00] DEBUG: Saving the current state of node karaf-mwrock-Windows2012R2
```

Second run:

```
[2018-06-29T15:42:47+00:00] DEBUG: Converging node karaf-mwrock-Windows2012R2
Recipe: aet::user
    * windows_user[example] action create[2018-06-29T15:42:47+00:00] INFO: Processing windows_user[example] action create (aet::user line 1)
[2018-06-29T15:42:47+00:00] INFO: Processing windows_user[example] action create (aet::user line 1)
[2018-06-29T15:42:47+00:00] DEBUG: Providers for generic windows_user resource enabled on node include: [Chef::Provider::User::Windows]
[2018-06-29T15:42:47+00:00] DEBUG: Providers for generic windows_user resource enabled on node include: [Chef::Provider::User::Windows]
[2018-06-29T15:42:47+00:00] DEBUG: Provider for action create on resource windows_user[example] is Chef::Provider::User::Windows
[2018-06-29T15:42:47+00:00] DEBUG: Provider for action create on resource windows_user[example] is Chef::Provider::User::Windows
[2018-06-29T15:42:47+00:00] DEBUG: windows_user[example] password has changed
[2018-06-29T15:42:47+00:00] DEBUG: windows_user[example] password has changed
[2018-06-29T15:42:47+00:00] INFO: windows_user[example] altered
[2018-06-29T15:42:47+00:00] INFO: windows_user[example] altered

    - alter user example
[2018-06-29T15:42:47+00:00] DEBUG: Saving the current state of node karaf-mwrock-Windows2012R2
```

## Stacktrace

N/A

### PR DESCRIPTION
**Pull request by stuartpreston**
### Description

This change catches the case where an empty string can be used to a set a password in Windows but then later cannot be used to validate the credentials have not changed when there is an account restriction in effect on the target node.  We now log that the credentials could not be validated due to an account restriction and assume that the credentials passed in were valid.  This allows the `:create` action on the user resource on Windows to not fail on the 2nd run when used with a blank password.

Functional Tests were split out into testing with and without a blank password.

### Issues Resolved

Fixes #7412 

### Check List

- [x] New functionality includes tests
- [x] All tests pass
- [x] RELEASE\_NOTES.md, has been updated if required (not required for bugfixes, required for API changes)
- [x] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

### CODE REVIEW

**Comment by tas50** [comment]
@stuartpreston You have some spec failures on appveyor

**Comment by stuartpreston** [comment]
@tas50 Yes, in fact this has stopped a bad change getting in. The behavior is different between Windows 10, Windows Server 2016 via a Packer’d Vagrant box and the Appveyor Windows Server 2016 in this case. I need to have a rethink about this change.

File: lib/chef/util/windows/net_user.rb [hunk 1]
```diff
@@ -96,8 +96,13 @@ def validate_credentials(passwd)
     token = Security.logon_user(@username, nil, passwd,
                LOGON32_LOGON_NETWORK, LOGON32_PROVIDER_DEFAULT)
     true
-  rescue Chef::Exceptions::Win32APIError
-    false
+  rescue Chef::Exceptions::Win32APIError => e
+    if e.to_s.include? "The user name or password is incorrect"
```
Comment (btm) [inline lib/chef/util/windows/net_user.rb]: Are these error strings localized? What's the error code that's raised? That should be printed as well by `Chef::Exceptions::Win32APIError` and wouldn't change. Is it 1326 / ERROR_LOGON_FAILURE?. 

It is too bad that `Chef::ReservedNames::Win32::Error.raise!` doesn't pass the code such that you could just check `e.code`.

File: lib/chef/util/windows/net_user.rb [hunk 2]
```diff
@@ -96,8 +96,13 @@ def validate_credentials(passwd)
...
+      return false
+    end
+    # all other exceptions will assume we cannot logon for a different reason (e.g. an Account Restriction)
+    Chef::Log.trace("Unable to login with the specified credentials. Assuming the credentials are valid.")
```
Comment (btm) [inline lib/chef/util/windows/net_user.rb]: I have a feeling some day we're going to find we're swallowing an exception here that we're interested in. Since this is already waaay down in trace, could we add a `Chef::Log.trace(e.msg)` after this?

File: spec/functional/resource/user/windows_spec.rb [hunk 3]
```diff
@@ -44,29 +46,138 @@ def delete_user(u)
...
+      PasswordComplexity = 0
+      [Version]
+      signature="$CHICAGO$"
+      Revision=1
+    EOF
+    windows_template_path = temp_security_template.path.gsub("/") { "\\" }
+    security_command = "secedit /configure /db #{temp_security_database} /cfg #{windows_template_path} /areas SECURITYPOLICY"
+    temp_security_template.write(file_content)
+    temp_security_template.close
+    puts security_command
```
Comment (btm) [inline spec/functional/resource/user/windows_spec.rb]: cruft

File: spec/functional/resource/user/windows_spec.rb [hunk 4]
```diff
@@ -44,29 +46,138 @@ def delete_user(u)
     shell_out("net user #{u} /delete")
   end
 
-  before do
+  def backup_secedit_policy
+    backup_command = "secedit /export /cfg #{ENV['TEMP']}\\secedit_restore.inf /areas SECURITYPOLICY"
+    system(backup_command)
```
Comment (btm) [inline spec/functional/resource/user/windows_spec.rb]: are you intentionally using `system` instead of `shell_out`? personal preference or is there a reason that should be put in a comment?

File: lib/chef/util/windows/net_user.rb (hunk 1 above)
Comment (stuartpreston) [reply lib/chef/util/windows/net_user.rb]: Right, so I've extended Win32APIError so you can now check `e.code` and not have to deal with localization.

File: lib/chef/util/windows/net_user.rb (hunk 2 above)
Comment (stuartpreston) [reply lib/chef/util/windows/net_user.rb]: Addressed.

File: spec/functional/resource/user/windows_spec.rb (hunk 3 above)
Comment (stuartpreston) [reply spec/functional/resource/user/windows_spec.rb]: Addressed.

File: spec/functional/resource/user/windows_spec.rb (hunk 4 above)
Comment (stuartpreston) [reply spec/functional/resource/user/windows_spec.rb]: No preference, I'm just used to calling `system()` - I've switched them to `shell_out` for consistency.

**Comment by stuartpreston** [comment]
Latest commits address feedback, and improves Win32APIError.  Assuming the CI tests run, please review @btm

**Comment by stuartpreston** [comment]
Looks like some Appveyor/Windows 2016 kinks to resolve...
