### PR TITLE
Fix #4949 and Avoid Errno::EBUSY on docker containers

### LINKED ISSUE #4949: Automatically set atomic_updates to false in Chef::Provider::File when updating /etc/resolv.conf or /etc/hosts on a docker guest?
These give EBUSY errors on docker.

Fixing them in cookbooks is a bit of a whack-a-mole.

The worst things that I can think of happening is:

- docker detection code fails to detect docker, so the updates fail, in which case manually setting atomic_updates to false works, and the user isn't much worse off than they are now.

- docker no longer requires these settings, in which case its still going to work, outside of the edge condition where you happen to run the server out of disk space right when you're doing this (but its docker, so immutable infrastructure magically makes this problem go away #amirite?)

It does mean that to fix bugs in the docker detection code you need to upgrade chef and not just upgrade a cookbook.  This doesn't feel like docker is going to mess with this that much though.

### PR DESCRIPTION
**Pull request by andrewjamesbrown**
This commit fixes https://github.com/chef/chef/issues/4949 by adding
ohai-based docker detection code and statically checking for
/etc/hostname or /etc/resolv.conf.

cc @lamont-granquist

### CODE REVIEW

File: lib/chef/provider/file.rb [hunk 1]
```diff
@@ -193,6 +199,12 @@ def manage_symlink_access?
 
       private
 
+      # Return true if we are running in a docker guest, or false otherwise.
+      def docker_guest?(node)
```
Comment (lamont-granquist) [inline lib/chef/provider/file.rb]: ideally i'd like to see `#docker?` pulled into Chef::DSL::Universal from chef-sugar:  

https://github.com/sethvargo/chef-sugar/blob/b9b3b643c27a0828f56d7355bb4d05577bd90a38/lib/chef/sugar/docker.rb

Comment (lamont-granquist) [inline lib/chef/provider/file.rb]: (i don't know exactly what to do about back-compat with chef-sugar and how to deal with the way that chef-sugar has that method which takes a node as an argument or what that use case covers...)

File: lib/chef/provider/file.rb [hunk 2]
```diff
@@ -67,7 +67,13 @@ class File < Chef::Provider
       def initialize(new_resource, run_context)
         @content_class ||= Chef::Provider::File::Content
         if new_resource.respond_to?(:atomic_update)
-          @deployment_strategy = Chef::FileContentManagement::Deploy.strategy(new_resource.atomic_update)
+          # Resolves https://github.com/chef/chef/issues/4949
+          if docker_guest?(run_context.node) && (new_resource.path == "/etc/resolv.conf" ||
+                                                 new_resource.path == "/etc/hostname")
+            @deployment_strategy = Chef::FileContentManagement::Deploy.strategy(false)
+          else
+            @deployment_strategy = Chef::FileContentManagement::Deploy.strategy(new_resource.atomic_update)
```
Comment (lamont-granquist) [inline lib/chef/provider/file.rb]: this could probably look more like:

```ruby
atomic_updates = special_docker_files? ? false : new_resource.atomic_updates
@deployment_strategy = Chef::FileContentManagement::Deploy.strategy(atomic_updates)
```

also should probably compare against `Pathname.cleanpath(new_resource.path)` and/or use `File.expand_path()`

Comment (coderanger) [inline lib/chef/provider/file.rb]: I feel like an explicit value in `new_resource.atomic_updates` should always override, just that the default becomes path-dependent.

Comment (lamont-granquist) [inline lib/chef/provider/file.rb]: yeah, probably should.

Comment (andrewjamesbrown) [inline lib/chef/provider/file.rb]: Added this behaviour with d801443.

**Comment by andrewjamesbrown** [comment]
I've updated the implementation so that `new_resource.atomic_updates` always overrides the default, and also moved the implementation of `docker?` into `lib/chef/dsl/platform_introspection.rb`.  I wasn't able to use the same code as chef-sugar, as Travis was complaining bitterly about the `File.exists?` and mocking that everywhere with docker-specific code didn't seem to be the best option, so I'm just looking at Ohai data.

**Comment by lamont-granquist** [comment]
mmm yeah, file provider unit tests and mocking `File.exists?`...   there be dragons...

**Comment by lamont-granquist** [comment]
👍

**Comment by smurawski** [comment]
👍
