### PR TITLE
[CHEF-8422] Fix incorrect deprecation warnings

### LINKED ISSUE #8422: knife bootstrap command shows deprecated warning even if we are using new key values for --winrm-user, --winrm-password, --winrm-port
## Description
knife bootstrap winrm command shows warning for the deprecated keys even we are using new key values while running the command. 

Following is the command 
``` knife bootstrap winrm azure@<ip-address> --node-name vj-win2012r2 --connection-user 'username' --connection-password 'password' --connection-port 5985 -c ~/workspace/chef-repo/.chef/config.rb ```

## Chef Version
```VJ:~$ chef-client -v
Chef Infra: 15.0.235
```
## Platform Version
Does not matter as its from workstation which is Ubuntu 18.04

## Replication Case
Run knife bootstrap winrm command as mentioned above

## Client Output

```

```

## Stacktrace
```
VJ:~$ knife bootstrap winrm azure@137.117.17.107 --node-name vj-win2012r2 --connection-user 'azure' --connection-password 'azure@12345678' --connection-port 5985 -c ~/workspace/chef-repo/.chef/config.rb -VV
INFO: Using configuration from /home/msys/workspace/chef-repo/.chef/knife.rb
WARNING: --winrm-user USER is deprecated. Use --connection-user USERNAME instead.
WARNING: --winrm-password is deprecated. Use --connection-password PASSWORD instead.
WARNING: --winrm-port is deprecated. Use --connection-port PORT instead.
Creating new client for vj-win2012r2
Creating new node for vj-win2012r2
Connecting to winrm
```

### PR DESCRIPTION
**Pull request by marcparadise**
## Description

Fixed incorrect option mapping where deprecated flags
would have a 'long' taken from the replacement flag. This caused 
mixlib-cli to duplicate the `long` flag - which caused lots of 
assignment confusion, including warning the operator about using flags they never used. 

This also updates the behavior in case of conflicting flags
(for example --ssh-user and --connection-user) to raise an error 
instead of choosing which one to use.This seems less likely to surprise.

Renamed deprecation variables and methods for readability/consistency.

Signed-off-by: Marc A. Paradise <marc.paradise@gmail.com>

## Related Issue

Fixes #8422 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I have run the pre-merge tests locally and they pass.
- [x] I have ~added~ updated to cover my changes.
- [x] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

File: lib/chef/knife/bootstrap.rb [hunk 1]
```diff
@@ -370,14 +367,12 @@ class Bootstrap < Knife
...
-        new_flag_name = new_long.split(" ").first
-
-        option(flag, long: new_long,
-               description: "#{old_long} is deprecated. Use #{new_long} instead.",
-               boolean: options[new_flag][:boolean])
+      DEPRECATED_FLAGS.each do |deprecated_key, deprecation_entry|
+        new_key, deprecated_long = deprecation_entry
+        new_long = options[new_key][:long]
+        option(deprecated_key, long: deprecated_long,
+                               description: "#{deprecated_long} is deprecated. Use #{new_long} instead.",
```
Comment (marcparadise) [inline lib/chef/knife/bootstrap.rb]: Outside of rename/relocate in file, the actual change was here. We were previously specifying `long: new_long`, which was incorrect. This now correctly uses `deprecated_long`.

File: lib/chef/knife/bootstrap.rb [hunk 2]
```diff
@@ -370,14 +367,12 @@ class Bootstrap < Knife
...
-        new_flag, old_long = new_flag_config
-        new_long = options[new_flag][:long]
-        new_flag_name = new_long.split(" ").first
-
-        option(flag, long: new_long,
-               description: "#{old_long} is deprecated. Use #{new_long} instead.",
-               boolean: options[new_flag][:boolean])
+      DEPRECATED_FLAGS.each do |deprecated_key, deprecation_entry|
+        new_key, deprecated_long = deprecation_entry
+        new_long = options[new_key][:long]
```
Comment (marcparadise) [inline lib/chef/knife/bootstrap.rb]: Outside of rename/relocate in file, the actual change was here. We were previously specifying `long: new_long`, which was incorrect. This now correctly uses `deprecated_long`.
