### PR TITLE
reconfigure between runs when running in a loop

### LINKED ISSUE #4578: SIGHUP kills chef-client when loading library in client.rb
Hello,

When loading a library in the /etc/chef/client.rb (using the attributes) we get the following code in the client.rb

```
["sbp_nagios_chefclient_handler/sbp_nagios_chefclient_handler"].each do |lib|
  begin
    require lib
  rescue LoadError
    Chef::Log.warn "Failed to load #{lib}. This should be resolved after a chef run."
  end
end
```

when sending a SIGHUP (kill -1) to the chef-client to reload the configuration, the chef-service client dies

```
[2016-02-15T15:13:33+01:00] FATAL: Configuration error ThreadError: can't be called from trap context
[2016-02-15T15:13:33+01:00] FATAL:   /etc/chef/client.rb:3:in `block in from_string'
[2016-02-15T15:13:33+01:00] FATAL:   /etc/chef/client.rb:1:in `each'
[2016-02-15T15:13:33+01:00] FATAL:   /etc/chef/client.rb:1:in `from_string'
[2016-02-15T15:13:33+01:00] FATAL: Aborting due to error in '/etc/chef/client.rb'
```

This only happens when loading the library, for the second time due to the sighup.
Tested with a empty library, to exclude code issues:

```
require 'chef/handler'
require 'chef/config'

class SBP
  class Nagios
    class Chefclient
      class Handler < ::Chef::Handler
        def initialize
        end
      end
    end
  end
end
```

Tested on RHEL7 with Chef-client 12.4.3 and 12.7.2
This is especially important because the SIGHUP signal gets sent every sunday in the default logrotate configuration on linux, and this crashing chef-client every week when using libraries.

Temporary workarround is doing a restart instead of reload in logrotate for rhel7 and systemd alike, but it would be better if chef-client handles this correctly.

```
override['chef_client']['log_rotation']['postrotate'] = 'systemctl restart chef-client.service >/dev/null || :'
```

Kind Regards,

### PR DESCRIPTION
**Pull request by btm**
We can't reconfigure in a trap context because we might open files or another activity that could cause a deadlock. Ruby 2.0+ now prevents this by raising a ThreadError.

Fixes #4578, Replaces #6119.

### CODE REVIEW

**Comment by btm** [comment]
@NimishaS This is what I was thinking, but needs testing. I haven't tried it yet.

**Comment by btm** [comment]
I fixed the chefspec issue but there are a couple failing tests to look at.

**Comment by NimishaS** [comment]
@btm, please cherry-pick https://github.com/MsysTechnologiesllc/chef/commit/784dfe4e2779e49e1fb84dadcf56d657726a81f1

**Comment by btm** [comment]
@chef/client-maintainers this is ready for review.

**Comment by danielsdeleo** [comment]
This LGTM. I almost wonder if we should just reconfigure regardless, though that could be a who moved my cheese thing.

**Comment by lamont-granquist** [comment]
i suspect you need to copypasta everything from client.rb to solo.rb as well still.

File: lib/chef/application/client.rb [hunk 1]
```diff
@@ -454,11 +460,12 @@ def interval_run_chef_client
   end
 
   def sleep_then_run_chef_client(sleep_sec)
-    @signal = test_signal
-    unless @signal == IMMEDIATE_RUN_SIGNAL
-      Chef::Log.debug("Sleeping for #{sleep_sec} seconds")
-      interval_sleep(sleep_sec)
-    end
```
Comment (lamont-granquist) [inline lib/chef/application/client.rb]: i'm a little bit confused as to what this logic used to do and what happens to it now

**Comment by lamont-granquist** [comment]
what is the downside of always reconfiguring?  it seems preferable since it ensures that the running daemon always has the current config.  this solution leaves open the possibility that the "external" code which updates the config will fail to correctly signal a reconfiguration and the event will get lost and the old config will remain running.  i'm more worried about that edge case causing user issues than the edge case of people who really want to update config and not have the daemon pick up that config...

File: lib/chef/application/client.rb (hunk 1 above)
Comment (btm) [inline lib/chef/application/client.rb]: client client starts, you come into sleep_then_run_chef_client, you haven't had any signals yet because you just started so you go into interval_sleep

in interval_sleep, we hang out and watch the pipe. If something hits it, we're going to drop back out below on 466. One of two things will hit the pipe. An `RECONFIGURE_SIGNAL` (H) will cause us to reconfigure on 468. if it isn't that it is `IMMEDIATE_RUN` (1). In which case, we're about to run anyway, so let's do that (I could add a comment or a line here around 468 to be more clear about that).

Then we run on 471, and we're going to end up looping back around to the top of this method. `test_signal` used to use `interval_sleep` to look to see if anything was sitting in the pipe, but that's redundant because we're just about to call `interval_sleep` anyway, there's nothing happening in between. We don't need a quick check because `interval_sleep` with a longer timeout is still going to return as soon as you send a signal and a character gets dropped into the pipe, or is already there waiting because it was sent in the middle of a previous run.

This is a bit confusing, I tried to improve it which was part of why `test_signal` got renamed to `check_for_signal` but when I realized the above I just avoided it and it looks like I forgot to prune it.

**Comment by btm** [comment]
I *guess* always reconfiguring is fine? If you're doing something to your chef config that isn't atomic, you've probably built something fragile anyway. It feels like a significant albeit minimal change. I'll send a note to the dev list.

**Comment by btm** [comment]
https://discourse.chef.io/t/always-reconfigure-between-runs-when-daemonized/10931

**Comment by lamont-granquist** [comment]
Yeah, although I'd say we want to know if anyone would _actually_ be broken by this change, rather than _possibly_.

**Comment by btm** [comment]
Here's another fun *possibly*, could someone be depending on reconfigure running in the middle of their first chef run?

**Comment by lamont-granquist** [comment]
like the daemon gets the old config and the child run gets the new, then you go back to the daemon with the old config?

**Comment by btm** [comment]
Like I bootstrap with a minimal client config, and during my first run I
drop some ruby in there, and reconfigure, which is necessary for my run to
finish correctly.

But I realize now I'd just call reconfigure, I would use a signal.

**Comment by btm** [comment]
If we always reconfigured there's a choice to make if we do it at the end of a run or the beginning of a run.

If you do it at the end of a run, you pick up any changes during the last run.

If you do it before a run, you are sure that you close and reopen log files before a run in case they've been rotated (the most common reason we get a HUP I think).

So we might want to still do both. Reconfigure at the end of every run, and reconfigure if we get a HUP while sleeping.

File: lib/chef/application/client.rb [hunk 2]
```diff
@@ -474,31 +481,33 @@ def sleep_then_run_chef_client(sleep_sec)
...
+        reconfigure
+        interval_sleep(sleep)
+      end
     else
-      # Windows
       sleep(sec)
     end
   end
 
-  def client_sleep(sec)
```
Comment (btm) [inline lib/chef/application/client.rb]: I merged this back into `interval_sleep` to have one less method with 'sleep' in it's name that wasn't very descriptive.

File: lib/chef/application/client.rb (hunk 1 above)
Comment (btm) [inline lib/chef/application/client.rb]: We didn't use `@signal` anywhere else so I moved all the signal code here into `interval_sleep` and added an explicit line for `IMMEDIATE_RUN` for clarity.

**Comment by btm** [comment]
> i suspect you need to copypasta everything from client.rb to solo.rb as well still.

I'm going to leave HUP as is in `application.rb` for solo, as it lacks any of the pattern for queueing signals that the client has. We could add that to solo if/when.

I've pushed a new commit that runs `reconfigure` at the end of every run.

**Comment by btm** [comment]
I can't find an un-horrific way way to add unit tests for hup behavior because of forking the process to be able to signal it.

**Comment by lamont-granquist** [comment]
yeah i wouldn't overly worry about that, those kinds of tests are very hard to write

**Comment by NimishaS** [comment]
@btm, I tested this PR. It's working fine.

**Comment by btm** [comment]
@chef/client-maintainers re-review?

**Comment by btm** [comment]
No responses to the [discourse post](https://discourse.chef.io/t/always-reconfigure-between-runs-when-daemonized/10931). I also tried pinging @jaymzh directly on slack but didn't hear back.
