### PR TITLE
Don't blindly check source on candidate_version calls.

### LINKED ISSUE #4819: chef-client 12.8.1.1 package remove doesn't work without source attr
## Description

excerpt from cookbook file:

```
package 'bos.adt.libm' do
   action :remove
end
```

It doesn't matter, if the package installed or not, the following error appears:

```
Chef::Exceptions::Package: package[bos.adt.libm] (cookbook::recipe line 89) had an error:  Chef::Exceptions::Package: installp -L -d  - ---- Begin output of installp -L -d  ----
STDOUT:
STDERR: installp: option requires an argument -- d
Usage installp:  Install Software:  Apply Only (-a) or Apply/Commit (-ac):
  installp [-R Path] {-a | -ac[N]} [-e LogFile] [-V Number] [-d Device]
           [-bBDEIpqQSvwX] [-F | -g] [-O{[r][s][u]}] [-t SaveDirectory]
           [-z BlockSize] { FileSet [Level] ... | -f ListFile | all }

Usage installp:  Commit (-c), Reject (-r), or Deinstall (-u) Software:
  installp [-R Path] {-c | -r | -u} [-e LogFile] [-V Number] [-bgpvwX]
           [-O{[r][s][u]}] { FileSet [Level] ... | -f ListFile | all }
  Note:  The keyword "all" is not valid with the -r or -u flag.

Usage installp:  Clean Up Install Failure (-C):
   installp [-R Path] -C [-e LogFile] [-b]

Usage installp:  List Software on Media (-l or -L):
   installp {-l[E] | -L} [-M Platform] [-e LogFile] [-d Device]
              [-BIqS] [-O{[s][u]}] [-z BlockSize]

Usage installp:  Commit (-c), Reject (-r), or Deinstall (-u) Software:
   installp [-R Path] {-c | -r | -u} [-e LogFile] [-V Number] [-bgpvwX]
            [-O{[r][s][u]}] { FileSet [Level] ... | -f ListFile | all }
   Note:  The keyword "all" is not valid with the -r or -u flag.

Usage installp:  List Fixes (-A) or Supplemental Information (-i):
   installp {-A | -i} [-e LogFile] [-d Device] [-BIqSw] [-O{[s][u]}]
              [-z BlockSize] { FileSet [Level] ... | -f ListFile | all }

Usage installp:  Valid Flags are AaBbCcDdeEFfgIiLlMNOpQqRrSstuVvwXYz where:

   -A  List fixes                      -M  {A|I|N|R} platform
   -a  Apply software                  -N  Do not save replaced files
   -B  Consider updates only           -O  {[r][s][u]}  root, share, usr
   -b  No bosboot                      -p  Preview
   -C  Cleanup install failure         -Q  Suppress instreq failures
   -c  Commit update(s)                -q  Quiet (no prompt)
   -D  Delete install image after      -R  {User Specified Install Location}
       successful installation.        -r  Reject update(s)
   -d  {install device}                -S  Suppress multi-volume processing
   -E  Display license agreements      -s  List applied software updates
   -e  {log file}                      -t  {alternate save directory}
   -F  Force installation              -u  Deinstall (Remove) fileset(s)
   -f  {file containing fileset(s)}    -V  {verbosity level [2-4]}
   -g  Include requisite software      -v  Verify installation
   -I  Consider base levels only       -w  No wildcarding
   -i  List supplemental information   -X  Expand filesystem if necessary
   -L  List software (colon separated) -Y  Accept new license agreements
   -l  List software on media          -z  {media block size}
---- End output of installp -L -d  ----
Ran installp -L -d  returned 99!
```
## Chef Version

chef-client LPP 12.8.1.1
## Platform Version

AIX 7.1

```
$ oslevel -s
7100-03-05-1524
```
## Replication Case

see above
## Client Output

see above
## Stacktrace

```
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/provider/package/aix.rb:98:in `candidate_version'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/provider/package.rb:471:in `candidate_version_array'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/provider/package.rb:452:in `block in each_package'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/provider/package.rb:451:in `each'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/provider/package.rb:451:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/provider/package.rb:451:in `each_package'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/provider/package.rb:437:in `forced_packages_missing_candidates'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/provider/package.rb:69:in `block in define_resource_requirements'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/mixin/why_run.rb:314:in `assert'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/provider/package.rb:67:in `define_resource_requirements'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/provider/package/aix.rb:35:in `define_resource_requirements'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/provider.rb:131:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/resource.rb:596:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/runner.rb:73:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/runner.rb:105:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/runner.rb:105:in `each'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/runner.rb:105:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/resource_collection/resource_list.rb:84:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/resource_collection/resource_list.rb:82:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/runner.rb:104:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/client.rb:668:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/client.rb:663:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/client.rb:663:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/client.rb:702:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/client.rb:280:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/application.rb:270:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/application.rb:258:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/application.rb:258:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/application.rb:223:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/application.rb:211:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/application/client.rb:445:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/application/client.rb:435:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/application/client.rb:435:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/application/client.rb:424:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/application.rb:58:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/bin/chef-client:26:in `<top (required)>'
```

/bin/chef-client:50:in `load'
/bin/chef-client:50:in`<main>'
### NOTE: CHEF CLIENT BUGS ONLY

The problem is in the candidate_version function. It tries to run installp with new_resource.source parameter without checking, if it is specified in the resource or not. When a package is being removed, there is no source directory for packages and installp -Ld <dir> fails. If you would like to check version, you must use lslpp -L (or lslpp -Lc) package for already installed packages, not installp.

As for me the following fixed the problem:

```
$ diff -c aix.rb aix.rb.orig
*** aix.rb      Mon Apr 11 12:33:25 2016
--- aix.rb.orig Mon Apr 11 12:31:16 2016
***************
*** 84,106 ****

          def candidate_version
            return @candidate_version if @candidate_version
!           if @new_resource.source
!             @package_source_found = ::File.exists?(@new_resource.source)
!             if @package_source_found
!               ret = shell_out_with_timeout("installp -L -d #{@new_resource.source}")
!               ret.stdout.each_line do |line|
!                 case line
!                 when /\w:#{Regexp.escape(@new_resource.package_name)}:(.*)/
!                   fields = line.split(":")
!                   @candidate_version = fields[2]
!                   @new_resource.version(fields[2])
!                   Chef::Log.debug("#{@new_resource} setting install candidate version to #{@candidate_version}")
!                 end
!               end
!               unless ret.exitstatus == 0
!                 raise Chef::Exceptions::Package, "installp -L -d #{@new_resource.source} - #{ret.format_for_exception}!"
!               end
              end
            end
            @candidate_version
          end
--- 84,101 ----

          def candidate_version
            return @candidate_version if @candidate_version
!           ret = shell_out_with_timeout("installp -L -d #{@new_resource.source}")
!           ret.stdout.each_line do |line|
!             case line
!             when /\w:#{Regexp.escape(@new_resource.package_name)}:(.*)/
!               fields = line.split(":")
!               @candidate_version = fields[2]
!               @new_resource.version(fields[2])
!               Chef::Log.debug("#{@new_resource} setting install candidate version to #{@candidate_version}")
              end
+           end
+           unless ret.exitstatus == 0
+             raise Chef::Exceptions::Package, "installp -L -d #{@new_resource.source} - #{ret.format_for_exception}!"
            end
            @candidate_version
          end
```

### PR DESCRIPTION
**Pull request by juliandunn**
This fixes #4819 with the fix suggested by the original poster.

### CODE REVIEW

**Comment by lamont-granquist** [comment]
Was this already fixed in 12.10.x by the lazy candidate_version patches in #4869?  and if its not, is there some (other) bug in the provider where it is greedily accessing candidate_version in remove when it doesn't have to?

**Comment by lamont-granquist** [comment]
since nothing else in the aix package provider hits candidate_version (at least not that grep turns up) it kinda looks like #4869 should have fixed this and this patch is now unnecessary.

**Comment by juliandunn** [comment]
I suspect there is some other bug as I tested a pretty recent 12.10.x and this kept occurring. I will try again with the latest 12.10.x

**Comment by lamont-granquist** [comment]
not impossible its still a bug but the original ticket was clearly before the lazy candidate version stuff went in...

**Comment by thommay** [comment]
@juliandunn did you get a chance to retest this?

**Comment by juliandunn** [comment]
@thommay yeah, just tested and it still exists in 12.15.19 on AIX. Same issue as in #4819.

File: lib/chef/provider/package/aix.rb [hunk 1]
```diff
@@ -88,19 +88,24 @@ def load_current_resource
...
-          ret.stdout.each_line do |line|
-            case line
-            when /\w:#{Regexp.escape(@new_resource.package_name)}:(.*)/
-              fields = line.split(":")
-              @candidate_version = fields[2]
-              @new_resource.version(fields[2])
-              Chef::Log.debug("#{@new_resource} setting install candidate version to #{@candidate_version}")
+          if @new_resource.source
+            @package_source_found = ::File.exists?(@new_resource.source)
+            if @package_source_found
```
Comment (lamont-granquist) [inline lib/chef/provider/package/aix.rb]: since this is getting copypasta'd around you probably want to consolidate this code now:

```
def package_source_found?
  @package_source_found ||= new_resource.source && ::File.exist?(new_resource.source)
end
```

then you can just `if package_source_found?` here.

Comment (lamont-granquist) [inline lib/chef/provider/package/aix.rb]: yeah please make that fix, and change the code in load_current_resource and define_resource_requirements as well, it'll make it a lot easier to understand what the problem is and that it is being solved correctly.  i think last time we reviewed this i had issues reading the code and understanding how the problem mapped to the code.

**Comment by juliandunn** [comment]
This is ready for review now. I'm pretty sure the 32-bit Windows failures are not related since Appveyor is saying "Invalid access to memory location. - CreateProcessW"

File: lib/chef/provider/package/aix.rb [hunk 2]
```diff
@@ -88,18 +85,20 @@ def load_current_resource
...
-          ret = shell_out_with_timeout("installp -L -d #{@new_resource.source}")
-          ret.stdout.each_line do |line|
-            case line
-            when /\w:#{Regexp.escape(@new_resource.package_name)}:(.*)/
-              fields = line.split(":")
-              @candidate_version = fields[2]
-              @new_resource.version(fields[2])
-              Chef::Log.debug("#{@new_resource} setting install candidate version to #{@candidate_version}")
+          if package_source_found?
+            ret = shell_out_with_timeout("installp -L -d #{@new_resource.source}")
```
Comment (stevendanna) [inline lib/chef/provider/package/aix.rb]: I know this is existing code, but in the spirit of leaving things better than we found them: The code from 89-98 looks really similar to the code from 53-62. Both appear to be extracting the version from a given package on disk. However, it isn't clear why this regex is different from those used above.  Could we consolidate this to a single function, perhaps with some comments?
