### PR TITLE
Flush package cache after attaching to rhsm subscription

### LINKED ISSUE #10722: rhsm_subscription doesn't clear cache leading to yum_package failures
## Description

When you attach to a new subscription using the `rhsm_subscription` resource and then the `package` resource to install something sourced from that subscription it fails.

## Chef Version

v15.3.8

## Platform Version

Red Hat Enterprise Linux 7.8

## Replication Case

```ruby
rhsm_subscription 'pool_id_goes_here'

package 'package_from_subscription'
```

I wish I could give a publicly available example but my use case is a private RPM in our internal Red Hat Satellite server.

## Client Output

```text
           * No candidate version available for package_from_subscription
           ================================================================================
           Error executing action `install` on resource 'yum_package[package_from_subscription]'
           ================================================================================

           Chef::Exceptions::Package
           -------------------------
           No candidate version available for package_from_subscription

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/test-cookbook/recipes/default.rb
            33: package 'package_from_subscription'
            34: 

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/test-cookbook/recipes/default.rb:33:in `from_file'
           yum_package("package_from_subscription") do
             package_name "package_from_subscription"
             action [:install]
             default_guard_interpreter :default
             declared_type :package
             cookbook_name "test-cookbook"
             recipe_name "default"
           end

           System Info:
           ------------
           chef_version=15.13.8
           platform=redhat
           platform_version=7.8
           ruby=ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-linux]
           program_name=/opt/chef/bin/chef-client
           executable=/opt/chef/bin/chef-client
```

### PR DESCRIPTION
**Pull request by jasonwbarnett**
## Description

This will ensure that recently attached subscription packages will be resolved by Chef Infra Client.

## Related Issue

- Closes #10722

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by jasonwbarnett** [comment]
@lamont-granquist I kicked this off to get a conversation going.

File: lib/chef/resource/rhsm_subscription.rb [hunk 1]
```diff
@@ -32,11 +32,19 @@ class RhsmSubscription < Chef::Resource
         name_property: true
 
       action :attach, description: "Attach the node to a subscription pool." do
+        already_attached = subscription_attached?(new_resource.pool_id)
```
Comment (tas50) [inline lib/chef/resource/rhsm_subscription.rb:35]: This would thing could be even cleaner if we just killed off the execute
```
unless already_attached
  converge_by("attach subscription pool #{new_resource.pool_id}") do
    shell_out!("subscription-manager attach --pool=#{new_resource.pool_id}")
  end
end
```

That way the no-op doesn't show the execute in the logs. That's totally untested, but *should* work if the current stuff here works

File: lib/chef/resource/rhsm_subscription.rb [hunk 2]
```diff
@@ -32,11 +32,11 @@ class RhsmSubscription < Chef::Resource
...
-        execute "Attach subscription pool #{new_resource.pool_id}" do
-          command "subscription-manager attach --pool=#{new_resource.pool_id}"
-          default_env true
-          action :run
-          not_if { subscription_attached?(new_resource.pool_id) }
+        unless subscription_attached?(new_resource.pool_id)
+          converge_by("attach subscription pool #{new_resource.pool_id}") do
+            shell_out!("subscription-manager attach --pool=#{new_resource.pool_id}")
+          end
+          flush_cache
```
[the remark this answers is not in the document]
Comment (tas50) [reply lib/chef/resource/rhsm_subscription.rb:39]: you can just stick it all in the same converge_by. you'll only get a single log and you won't flush in why-run since we skip converge_by in why-run

[the remark this answers is not in the document]
Comment (jasonwbarnett) [reply lib/chef/resource/rhsm_subscription.rb:39]: Ah, that makes sense. I'll update and add tests. Thanks

**Comment by jasonwbarnett** [comment]
@tas50 I could really use some help. For the life of me I can't figure out how to intercept the `#shell_out!`. It keeps making it through and failing as a result. Help!

File: lib/chef/resource/rhsm_subscription.rb [hunk 3]
```diff
@@ -50,6 +50,8 @@ class RhsmSubscription < Chef::Resource
       end
 
       action_class do
+        include Chef::Mixin::ShellOut
```
Comment (jasonwbarnett) [inline lib/chef/resource/rhsm_subscription.rb:53]: Is this even necessary?

Comment (tas50) [reply lib/chef/resource/rhsm_subscription.rb:53]: that comes for free

**Comment by tas50** [comment]
@lamont-granquist Thoughts on this one?

File: lib/chef/resource/rhsm_subscription.rb [hunk 4]
```diff
@@ -32,11 +32,11 @@ class RhsmSubscription < Chef::Resource
...
       action :attach, description: "Attach the node to a subscription pool." do
-        execute "Attach subscription pool #{new_resource.pool_id}" do
-          command "subscription-manager attach --pool=#{new_resource.pool_id}"
-          default_env true
-          action :run
-          not_if { subscription_attached?(new_resource.pool_id) }
+        unless subscription_attached?(new_resource.pool_id)
+          converge_by("attach subscription pool #{new_resource.pool_id}") do
+            shell_out!("subscription-manager attach --pool=#{new_resource.pool_id}")
+            flush_cache
```
Comment (jasonwbarnett) [inline lib/chef/resource/rhsm_subscription.rb:38]: @lamont-granquist is this actually going to work? I couldn't find where `#flush_cache` is defined and have absolutely no confidence this is accurate. Well, I see that `#flush_cache` is defined in `Chef::Provider::Package::Dnf` and `Chef::Provider::Package::Yum`, but not seeing how this will be leverage in this context.

It seems like the behavior between `Chef::Provider::Package::Dnf` and `Chef::Provider::Package::Yum` is identical. Would you like me to abstract into a module and include in both `Chef::Provider::Package::Dnf` and `Chef::Provider::Package::Yum` and in this action class as well? Is there a better way here?

Comment (lamont-granquist) [reply lib/chef/resource/rhsm_subscription.rb:38]: Best thing to do would probably be to `build_resource(:package, "anything-goes").run_action(:flush_cache)`

Otherwise, no it doesn't work to try to call flush_cache there, that lives on an instance of the appropriate package provider and you can't get to it that way.  You could call Chef::Provider::Package::Dnf::PythonHelper.instance.restart, but that is an implementation detail of how flush_caching currently operates and I've certainly wanted it to stop doing that, so it shouldn't be considered a public API for this purpose.

File: lib/chef/resource/rhsm_subscription.rb [hunk 5]
```diff
@@ -32,11 +32,11 @@ class RhsmSubscription < Chef::Resource
...
       action :attach, description: "Attach the node to a subscription pool." do
-        execute "Attach subscription pool #{new_resource.pool_id}" do
-          command "subscription-manager attach --pool=#{new_resource.pool_id}"
-          default_env true
-          action :run
-          not_if { subscription_attached?(new_resource.pool_id) }
+        unless subscription_attached?(new_resource.pool_id)
+          converge_by("attach subscription pool #{new_resource.pool_id}") do
+            shell_out!("subscription-manager attach --pool=#{new_resource.pool_id}")
+            build_resource(:package, "rhsm_subscription-#{new_resource.pool_id}-flush_cache").run_action(:flush_cache)
```
Comment (jasonwbarnett) [inline lib/chef/resource/rhsm_subscription.rb:38]: @lamont-granquist  Will this also run the default action (i.e. `:install`)? Or is this all good?

File: spec/unit/resource/rhsm_subscription_spec.rb [hunk 6]
```diff
@@ -38,6 +48,35 @@
...
+      end
+    end
+
+    context "when not attached to pool" do
+      before do
+        allow(provider).to receive(:subscription_attached?).with(resource.pool_id).and_return(false)
+      end
+
+      it "attaches to pool" do
+        expect(provider).to receive(:shell_out!).with("subscription-manager attach --pool=#{resource.pool_id}")
```
Comment (jasonwbarnett) [inline spec/unit/resource/rhsm_subscription_spec.rb:69]: @lamont-granquist I am unable to figure out why this isn't working properly. When I run the unit tests it's still trying to run `#shell_out!` on the actual host instead of rspec catching it and responding with the mock.

File: lib/chef/resource/rhsm_subscription.rb (hunk 5 above)
Comment (jasonwbarnett) [reply lib/chef/resource/rhsm_subscription.rb:38]: In other words, do I need to do this?

```ruby
            build_resource(:package, "rhsm_subscription-#{new_resource.pool_id}-flush_cache") do
              action :nothing
            end.run_action(:flush_cache
```

**Comment by jasonwbarnett** [comment]
@lamont-granquist @tas50 I've spent about 2 hours trying to test this and everything I try leads down a rabbit hole. I don't know if this is indicative of a bad design (at a higher level) or a lack of skill on my part. Either way, would appreciate some guidance when ya'll have some time. Thank you

File: lib/chef/resource/rhsm_subscription.rb (hunk 5 above)
Comment (lamont-granquist) [reply lib/chef/resource/rhsm_subscription.rb:38]: no you're not using `declare_resource` so its not being put on the resource_collection and won't be converged by the normal process.  only the actions you run get run.

`build_resource` is just some magic around getting a `new` instance of the right package resource.

This also means that it won't cause the resource you are running to be updated when it updates -- which is why you shouldn't generally ever use build_resource and should at least use declare_resource -- but here we're doing it deliberately because we're flushing the cache and that has nothing to do with the underlying state of the machine changing.  Arguably using a resource for this is philosophically wrong, but its the public API that we have.

File: spec/unit/resource/rhsm_subscription_spec.rb [hunk 7]
```diff
@@ -38,6 +43,46 @@
...
+      dummy = Mixlib::ShellOut.new
+      allow_any_instance_of(Chef::Mixin::ShellOut).to receive(:shell_out!).with("subscription-manager attach --pool=#{resource.pool_id}").and_return(dummy)
+      allow(dummy).to receive(:stdout).and_return("Successfully attached a subscription for: My Subscription")
+      allow(dummy).to receive(:exitstatus).and_return(0)
+      allow(dummy).to receive(:error?).and_return(false)
+      node.automatic_attrs[:platform_family] = "rhel"
+      node.automatic_attrs[:platform_version] = "7.3"
+      allow_any_instance_of(Chef::Provider::Package::Yum).to receive(:installed_version).with(0).and_return(Chef::Provider::Package::Yum::Version.new(nil, nil, nil))
+      allow_any_instance_of(Chef::Provider::Package::Yum).to receive(:available_version).with(0).and_return(Chef::Provider::Package::Yum::Version.new(nil, nil, nil))
+      allow_any_instance_of(Chef::Provider::Package::Yum::PythonHelper).to receive(:close_rpmdb)
```
Comment (lamont-granquist) [inline spec/unit/resource/rhsm_subscription_spec.rb:57]: You're trying way too hard here.  You're testing that the details of the ResourceResolver correctly give back a Chef::Package::Provider::Yum when you're forcing the distro version, which is duplicating all the testing which goes on already to prove that happens.

I'd just create a double object and:

```
expect(provider).to receive(:build_resource).with(<stuff>).and_return(mydouble)
expect(mydouble).to receive(:run_action).with(:flush_cache)
```

File: spec/unit/resource/rhsm_subscription_spec.rb [hunk 8]
```diff
@@ -38,6 +43,46 @@
     expect { resource.action :remove }.not_to raise_error
   end
 
+  describe "#action_attach" do
+    before do
+      dummy = Mixlib::ShellOut.new
+      allow_any_instance_of(Chef::Mixin::ShellOut).to receive(:shell_out!).with("subscription-manager attach --pool=#{resource.pool_id}").and_return(dummy)
+      allow(dummy).to receive(:stdout).and_return("Successfully attached a subscription for: My Subscription")
+      allow(dummy).to receive(:exitstatus).and_return(0)
+      allow(dummy).to receive(:error?).and_return(false)
```
Comment (lamont-granquist) [inline spec/unit/resource/rhsm_subscription_spec.rb:52]: Here also you should stub at the level of:

```
so = instance_double(Mixlib::ShellOut)
expect(provider).to receive(:shell_out!).with(<...>).and_return(so)
```

**Comment by tas50** [comment]
@jasonwbarnett anything else we can do for you on this one?

**Comment by jasonwbarnett** [comment]
@lamont-granquist @tas50 I am pretty sure this is ready to go at this point. Please let me know if you see anything missing or sub-optimally done and I will correct. Thanks!

**Review by lamont-granquist — APPROVED** [review]
