### PR TITLE
Use new Net:SSH host key verify values

### LINKED ISSUE #8482: Bootstrap: If the SSH fingerprint is unknown offer to continue anyways
If we encounter an unknown ssh key we should offer to continue. Just about everyone is going to hit this and then have to start over with the flag to ignore the unknown keys.

```
Creating new client for tim_test
Creating new node for tim_test
Connecting to ec2-34-221-181-2.us-west-2.compute.amazonaws.com
ERROR: Train::Transports::SSHFailed: SSH command failed (fingerprint SHA256:ll/BKqLRTOgQXaFCFUaHx5/JxDYvOpAbSS80NVTek8Q is unknown for "ec2-34-221-181-2.us-west-2.compute.amazonaws.com,34.221.181.2")
```

### PR DESCRIPTION
**Pull request by btm**
Fixes #8482 by prompting to continue if the host key is not recognized.

This attempts to tell Net:SSH to accept and write the key but it is only
temporarily accepting.

This changes the parameters of --ssh-verify-host-key (which is new) to
take the Net::SSH values, which get passed through by train. This allows
the user more options than only verifying or not.

Signed-off-by: Bryan McLellan <btm@loftninjas.org>

### CODE REVIEW

File: lib/chef/knife/bootstrap.rb [hunk 1]
```diff
@@ -88,7 +88,7 @@ def self.friendly_opt_list(opt_array)
       option :winrm_auth_method,
         short: "-w AUTH-METHOD",
         long: "--winrm-auth-method AUTH-METHOD",
-        description: "The WinRM authentication method to use. Valid choices are #{friendly_opt_list(WINRM_AUTH_PROTOCOL_LIST)}.",
```
Comment (marcparadise) [inline lib/chef/knife/bootstrap.rb]: Why remove the valid values? The only other way to discover them is to try them and see if you get an error.

Comment (tas50) [inline lib/chef/knife/bootstrap.rb]: I get why we're doing this here, but we should get a todo to fix the output of "in" cleaned up since it's not very user friendly.

Comment (tas50) [reply lib/chef/knife/bootstrap.rb]: Also you might be able to kill that friendly_opt_list method now. I'm not sure if I was using that anywhere else

**Comment by tas50** [comment]
@btm can you add the flag changes to the release notes

File: lib/chef/knife/bootstrap.rb (hunk 1 above)
Comment (tas50) [reply lib/chef/knife/bootstrap.rb]: Using in prints them to help as well. It just does so in a kind of confusing way: 

```
-w AUTH-METHOD,                  The WinRM authentication method to use. Valid choices are 'plaintext', 'kerberos', 'ssl' and 'negotiate'. (included in ['plaintext', 'kerberos', 'ssl', 'negotiate'])
        --winrm-auth-method
```

File: lib/chef/knife/bootstrap.rb [hunk 2]
```diff
@@ -549,7 +549,28 @@ def run
...
+            hostname,ip = $2.split(',')
+            puts "The authenticity of host '#{hostname} (#{ip})' can't be established."
+            # TODO: convert the SHA256 base64 value to hex with colons
+            # 'ssh' example output:
+            # RSA key fingerprint is e5:cb:c0:e2:21:3b:12:52:f8:ce:cb:00:24:e2:0c:92.
+            # ECDSA key fingerprint is 5d:67:61:08:a9:d7:01:fd:5e:ae:7e:09:40:ef:c0:3c.
+            puts "fingerprint is #{fingerprint}."
+            ui.confirm("Are you sure you want to continue connecting")
+            # FIXME: this should save the key to known_hosts but doesn't appear to be
+            config[:ssh_verify_host_key] = :accept_new
```
Comment (marcparadise) [inline lib/chef/knife/bootstrap.rb]: train doesn't know about this value - it only expects a bool [1], so we'll need to modify there as well. 

That's probably also why `accept_new` isn't causing `known_hosts` to be updated.  

[1] https://github.com/inspec/train/blob/master/lib/train/transports/ssh.rb#L199

File: lib/chef/knife/bootstrap.rb [hunk 3]
```diff
@@ -549,7 +549,28 @@ def run
...
+        rescue Train::Transports::SSHFailed => e
+          if e.message =~ /fingerprint (\S+) is unknown for "(.+)"/
+            fingerprint = $1
+            hostname,ip = $2.split(',')
+            puts "The authenticity of host '#{hostname} (#{ip})' can't be established."
+            # TODO: convert the SHA256 base64 value to hex with colons
+            # 'ssh' example output:
+            # RSA key fingerprint is e5:cb:c0:e2:21:3b:12:52:f8:ce:cb:00:24:e2:0c:92.
+            # ECDSA key fingerprint is 5d:67:61:08:a9:d7:01:fd:5e:ae:7e:09:40:ef:c0:3c.
+            puts "fingerprint is #{fingerprint}."
```
Comment (marcparadise) [inline lib/chef/knife/bootstrap.rb]: recommend: #"#{hostname}'s fingerprint is: #{fingerprint}"

File: lib/chef/knife/bootstrap.rb (hunk 1 above)
Comment (btm) [reply lib/chef/knife/bootstrap.rb]: Yeah, we should fix that output, but it was weird having them printed twice.

File: lib/chef/knife/bootstrap.rb [hunk 4]
```diff
@@ -549,7 +549,28 @@ def run
 
         $stdout.sync = true
         register_client
-        connect!
+        begin
+          connect!
```
Comment (marcparadise) [inline lib/chef/knife/bootstrap.rb]: Can we rescue this rescue block of  `connect!` itself?  Having the connection error handling in one place seems more manageable than splitting it across two.

File: lib/chef/knife/bootstrap.rb [hunk 5]
```diff
@@ -549,7 +549,28 @@ def run
...
+          if e.message =~ /fingerprint (\S+) is unknown for "(.+)"/
+            fingerprint = $1
+            hostname,ip = $2.split(',')
+            puts "The authenticity of host '#{hostname} (#{ip})' can't be established."
+            # TODO: convert the SHA256 base64 value to hex with colons
+            # 'ssh' example output:
+            # RSA key fingerprint is e5:cb:c0:e2:21:3b:12:52:f8:ce:cb:00:24:e2:0c:92.
+            # ECDSA key fingerprint is 5d:67:61:08:a9:d7:01:fd:5e:ae:7e:09:40:ef:c0:3c.
+            puts "fingerprint is #{fingerprint}."
+            ui.confirm("Are you sure you want to continue connecting")
```
Comment (marcparadise) [inline lib/chef/knife/bootstrap.rb]: Does this raise if they pick no? If not, we need to check the return value before proceeding.

File: lib/chef/knife/bootstrap.rb (hunk 1 above)
Comment (marcparadise) [reply lib/chef/knife/bootstrap.rb]: :+1:

File: lib/chef/knife/bootstrap.rb (hunk 5 above)
Comment (btm) [reply lib/chef/knife/bootstrap.rb]: `#confirm` will exit 3 if they say no.

File: lib/chef/knife/bootstrap.rb (hunk 2 above)
Comment (btm) [reply lib/chef/knife/bootstrap.rb]: That method converts specific values but passes anything else through:

```
2.4.1 :001 > given = :accept_new
 => :accept_new 
2.4.1 :002 >         {
2.4.1 :003 >               'true' => true,
2.4.1 :004 >               'false' => false,
2.4.1 :005 >               nil => false,
2.4.1 :006 >             }.fetch(given, given)
 => :accept_new 
```

Comment (btm) [reply lib/chef/knife/bootstrap.rb]: you can see it working here too, notice after the SNIP in the first and second connections:

```
DEBUG: [SSH] opening connection to ubuntu@ec2-3-85-23-14.compute-1.amazonaws.com<{SNIP, :verify_host_key=>:always}>
The authenticity of host 'ec2-3-85-23-14.compute-1.amazonaws.com (3.85.23.14)' can't be established.
fingerprint is SHA256:dVvJdTZrMcAr+YfN0NV4tnt5Sj5zjdJLhfzEoZvkd90.
Are you sure you want to continue connecting? (Y/N) y

Connecting to ec2-3-85-23-14.compute-1.amazonaws.com
DEBUG: [SSH] Using Agent keys as no password or key file have been specified
DEBUG: [SSH] ubuntu@ec2-3-85-23-14.compute-1.amazonaws.com<{SNIP, :verify_host_key=>:accept_new}> (cmd.exe /c ver)
```

File: lib/chef/knife/bootstrap.rb (hunk 3 above)
Comment (btm) [reply lib/chef/knife/bootstrap.rb]: I was trying to match the output of `ssh` which is two lines, the first line with the hostname is above the comments here. the second one is in the example comments, but to do it we need to convert the key from base64 at least in the case of an RSA SHA256 fingerprint, and I kinda punted on that.

File: lib/chef/knife/bootstrap.rb (hunk 1 above)
Comment (btm) [reply lib/chef/knife/bootstrap.rb]: https://github.com/chef/mixlib-cli/pull/59

File: lib/chef/knife/bootstrap.rb (hunk 2 above)
Comment (marcparadise) [reply lib/chef/knife/bootstrap.rb]: Cool, thanks - that's what I get for skimming

File: lib/chef/knife/bootstrap.rb (hunk 4 above)
Comment (btm) [reply lib/chef/knife/bootstrap.rb]: done
