### PR TITLE
Fix for chocolatey_package fails using extra options

### LINKED ISSUE #8437: chocolatey_package fails using extra options
## Description
#8230 added options parameter while fetching list of available packages.  Some options that are allowed for choco install fail when running choco list.

## Chef Version
Showed up in 14.11.21, our TK dev instances saw this as recently as 2019-04-26.

## Platform Version
Windows, chef-client 14.11.21+

## Replication Case
```
chocolatey_package '<package-name>' do
 options '--install-arguments=NO_START=1'
end
```

## Client Output
From user report, if we need to add more, let us know.
```
No candidate version available for <package-name>
```

## Stacktrace
N/A

### PR DESCRIPTION
**Pull request by kapilchouhan99**
Signed-off-by: Kapil Chouhan <kapil.chouhan@msystechnologies.com>

## Description
- Added method `common_options(include_source: true)` and three properties `list_options`, `user` and `password`
- In the chocolatey package if we have the feature `useEnhancedExitCodes` turned on, at that time choco will provide enhanced exit codes:
   ```
    0: operation was successful, no issues detected
    –1 or 1: an error has occurred
    2: no results (enhanced)
   ```
   - If the feature is not enabled its provide normally Exit codes:
   ```
    0: operation was successful, no issues detected
    –1 or 1: an error has occurred
   ```
   - So we have handled the exception( 2: no results (enhanced) ) by setting the default value of property `returns` as [0, 2] instead of [0].
- Added test cases
- Ensured chef-style on the code changes made
## Related Issue
Fixes #8437

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [x] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by kapilchouhan99** [comment]
@btm @tas50 
In the choco, if we have the feature `useEnhancedExitCodes` turned on, then choco will provide enhanced exit codes(2: no results).
Choco exit codes https://chocolatey.org/docs/commandsinfo#exit-codes

Here we have 2 approaches to fix this:
1.) If we get exit status as 2, at that time we can raise a custom error like: "Package does not exist."
2.) Or we can skip it instead of raising an error on exit status 2, we can set the default value of property returns as [0, 2] instead of [0]

Please let me know your thoughts on this.

**Comment by nimDevOps** [comment]
My experience with https://github.com/chef/chef/issues/8437 is not about handling error code 2, but mostly splitting package parameters into two subsets:

1. Parameters applicable for "choco list" command like package Id and version;
2. Parameters applicable for package itself, for example for **git.install**:
 **--packageParameters="/NoAutoCrlf /GitAndUnixToolsOnPath"**
should not be sent to Choco Repository server;

I would say even more: only Id, version and new parameters used with authentication or whatever chef can recognize for this enhancement should be used with **choco list** command.

File: lib/chef/provider/package/chocolatey.rb [hunk 1]
```diff
@@ -282,6 +283,25 @@ def parse_list_output(*args)
...
+            password = options.include?("-p") ? find_credential("-p", options) : find_credential("--password", options)
+          end
+          [username, password].compact.join(" ").strip
+        end
+
+        def find_credential(element, array)
+          index = array.find_index(element) + 1
+          next_element = array.at(index)
+          next_element ? element + " " + next_element : nil
+        end
```
Comment (lamont-granquist) [inline lib/chef/provider/package/chocolatey.rb]: This now feels like we're going in the wrong direction trying to solve this problem.

We probably need to back up and add `new_resource.list_options` as something that users can set which is separate to `new_resource.options`.  For common things like user and password those should go onto additional `new_resource.user` and `new_resource.password` fields.

I could potentially be persuaded to avoid the duplication between `list_options` and `options` but then `options` should get passed to both, and any options which cannot apply to both then must be made into properties on the new_resource.

What I don't know is what the overlap looks like between the different options that those CLI commands support.  If the union is large, then users probably want `options` passed to both, if the union is small then users probably don't.  Based on the code here it looks like the union is small so that users probably want `options` to only go to the main install or remove command and that `new_resource.list_options` should be a separate.

Either way though we should just use properties instead of doing this parsing out of the options argument.  The creds are important enough they should be top-level properties.

**Comment by lamont-granquist** [comment]
so https://github.com/chef/chef/pull/7712 is closer to the correct direction to take this fix.  that's more what i'm talking about with suggesting user and password properties be explicit on the resource.

https://github.com/chef/chef/issues/8722 is also related to this problem.  we seem to have a general problem with some options that need to go to list and some options that can't.
