### PR TITLE
Fix failures in build_essential on rhel platforms

### LINKED ISSUE #9107: build_essential failing to run for CentOS
## Description
Using the build_essential on a CentOS 7 node now gives the following:

```
* build_essential[default] action install[2019-11-18T10:18:48-05:00] WARN:         The build_essential resource does not currently support the 'rhel' platform family. Skipping...
```

It would appear that the fedora_derived definition is not correctly encompassing RHEL platforms.

## Chef Version
Chef Infra Client version 15.5.9

## Platform Version
  "platform": "centos",
  "platform_version": "7.6.1810",
  "platform_family": "rhel",

## Replication Case
- Create a CentOS client.
- Run a cookbook that requires the build_essential resource.

## Client Output

```
* build_essential[default] action install[2019-11-18T10:18:48-05:00] WARN:         The build_essential resource does not currently support the 'rhel' platform family. Skipping...
```

### PR DESCRIPTION
**Pull request by lamont-granquist**
- fixes bug inside the action which was breaking build_essential on rhel
- wires up some more testing in the provider resolver spec
- adds a property that we can turn on so that this kind of breakage will raise an error in our end-to-end testing

i'm not entirely sure raise_if_unsupported true should be the default behavior, but that would be a breaking change and we definitely need to be able to bypass that for testing.

closes #9107

### CODE REVIEW

File: lib/chef/resource/build_essential.rb [hunk 1]
```diff
@@ -45,24 +45,29 @@ class BuildEssential < Chef::Resource
         description: "Install the build essential packages at compile time.",
         default: false, desired_state: false
 
+      property :raise_if_unsupported, [TrueClass, FalseClass],
+        description: "Raise a hard error on platforms where this resource is unsupported.",
+        default: false, desired_state: false # FIXME: make this default to true
```
Comment (tas50) [inline lib/chef/resource/build_essential.rb]: making the default to continue on when we don't do what the user says seems like a really big anti-pattern. if that's what the user wants then they should specify it. Shouldn't be the default

File: kitchen-tests/cookbooks/end_to_end/recipes/default.rb [hunk 2]
```diff
@@ -36,7 +36,9 @@
   only_if { platform_family?("rhel") }
 end
 
-build_essential
+build_essential do
+  raise_if_unsupported true
```
Comment (tas50) [inline kitchen-tests/cookbooks/end_to_end/recipes/default.rb]: We shouldn't be using this in the kitchen tests. It would be better to have it blow up in our faces when we add new platforms so we can make sure we add support for those.

File: lib/chef/resource/build_essential.rb (hunk 1 above)
Comment (lamont-granquist) [reply lib/chef/resource/build_essential.rb]: Its the current behavior, it would likely be breaking to change it

File: kitchen-tests/cookbooks/end_to_end/recipes/default.rb (hunk 2 above)
Comment (lamont-granquist) [reply kitchen-tests/cookbooks/end_to_end/recipes/default.rb]: Right but that's what it does now by raising?

Comment (tas50) [reply kitchen-tests/cookbooks/end_to_end/recipes/default.rb]: Slowly walking away from keyboard. Yep I'm an idiot
