### PR TITLE
Chef-15: Added deprecation check for short arguments

### LINKED ISSUE #8566: Old knife bootstrap windows winrm -x short arg should raise a deprecation
Before Chef 15 / knife-windows 3, running `knife bootstrap windows winrm` took a `-x USER` short flag. We've deprecated `--winrm-user` to `--connection-user` but we should also catch `-x` and tell the user to use `-U` instead. 

What you get right now is:
```
Error: invalid option: -x
[snip --help output]
```

### PR DESCRIPTION
**Pull request by Nimesh-Msys**
- Handles "-x" that was used to set "winrm-user" and is now Deprecated.
- Fixes #8566 

Signed-off-by: Nimesh-Msys <nimesh.patni@msystechnologies.com>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

File: lib/chef/knife/bootstrap.rb [hunk 1]
```diff
@@ -368,7 +369,7 @@ class Bootstrap < Knife
         ssl_peer_fingerprint:
           [:winrm_ssl_peer_fingerprint, "--ssl-peer-fingerprint FINGERPRINT"],
         winrm_user:
-          [:connection_user, "--winrm-user USER"],
+          [:connection_user, "--winrm-user USER", nil, "-x USERNAME"],
```
Comment (btm) [inline lib/chef/knife/bootstrap.rb]: seems like both options should use either USER or USERNAME here.

Comment (Nimesh-Msys) [reply lib/chef/knife/bootstrap.rb]: As per the previous implementation, I used [-x USERNAME](https://github.com/chef/chef/blob/chef-14/lib/chef/knife/bootstrap.rb#L48). If we choose to use USERNAME here, should we also update the same for ssh_user option ?

Comment (marcparadise) [reply lib/chef/knife/bootstrap.rb]: Let's make it consistently USERNAME across connection-user, winrm-user, ssh-user

File: lib/chef/knife/bootstrap.rb [hunk 2]
```diff
@@ -384,18 +385,28 @@ class Bootstrap < Knife
       }.freeze
 
       DEPRECATED_FLAGS.each do |deprecated_key, deprecation_entry|
-        new_key, deprecated_long, replacement_value = deprecation_entry
+        new_key, deprecated_long, replacement_value, deprecated_short = deprecation_entry
```
Comment (marcparadise) [inline lib/chef/knife/bootstrap.rb]: I think this is good for now, but it's getting unwieldy. I think we're at the point where if we add more, it might make sense to have a DeprecatedOption struct. 


With  I'm POCing some mixlib-install work that will manage deprecation behaviors there; but this is good for now.

File: spec/unit/knife/bootstrap_spec.rb [hunk 3]
```diff
@@ -1,6 +1,6 @@
 #
 # Author:: Ian Meyer (<ianmmeyer@gmail.com>)
-# Copyright:: Copyright 2010-2016, Ian Meyer
+# Copyright:: Copyright 2010-2019, Chef Software Inc.
```
Comment (btm) [inline spec/unit/knife/bootstrap_spec.rb]: We need to leave the original copyright here. We can add another line below it.

Comment (Nimesh-Msys) [reply spec/unit/knife/bootstrap_spec.rb]: Done. Thanks

**Comment by btm** [comment]
We'll take this for now. I believe @marcparadise is working on adding this upstream in mixlib-cli to fix https://github.com/chef/mixlib-cli/issues/63, so later we can back all of this out for the cleaner solution.
