### PR TITLE
ignore gid in the user resource on windows

### LINKED ISSUE #4024: Cannot create user on windows 2012R2
I am trying to create a user on windows 2012R2 (through poise_service_user resource used in consul cookbook) but it fails with the following error:

```
TypeError
---------
no implicit conversion of FFI::MemoryPointer into Integer
```

I can reproduce the issue with a very simple recipe:
```
user 'consul' do
  comment "Service user for consul"
  gid 'consul'
  shell '/bin/false'
  system true
end
```

The stacktrace is:
```
-----> Execute command on default-windows-2012r2.
       Generated at 2015-10-05 09:56:32 +0000
       TypeError: user[consul] (consul-criteo::test_user line 1) had an error: TypeError: no implicit conversion of FFI::MemoryPointer into Integer
       C:/opscode/chef/embedded/apps/chef/lib/chef/win32/api/net.rb:98:in `[]='
       C:/opscode/chef/embedded/apps/chef/lib/chef/win32/api/net.rb:98:in `set'
       C:/opscode/chef/embedded/apps/chef/lib/chef/win32/net.rb:113:in `block in net_user_add_l3'
       C:/opscode/chef/embedded/apps/chef/lib/chef/win32/net.rb:112:in `each'
       C:/opscode/chef/embedded/apps/chef/lib/chef/win32/net.rb:112:in `net_user_add_l3'
       C:/opscode/chef/embedded/apps/chef/lib/chef/util/windows/net_user.rb:118:in `add'
       C:/opscode/chef/embedded/apps/chef/lib/chef/provider/user/windows.rb:74:in `create_user'
       C:/opscode/chef/embedded/apps/chef/lib/chef/provider/user.rb:131:in `block in action_create'
       C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/why_run.rb:52:in `call'
       C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/why_run.rb:52:in `add_action'
       C:/opscode/chef/embedded/apps/chef/lib/chef/provider.rb:175:in `converge_by'
       C:/opscode/chef/embedded/apps/chef/lib/chef/provider/user.rb:130:in `action_create'
       C:/opscode/chef/embedded/apps/chef/lib/chef/provider.rb:140:in `run_action'
       C:/opscode/chef/embedded/apps/chef/lib/chef/resource.rb:584:in `run_action'
       C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
       C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
       C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
       C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
       C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
       C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
       C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
       C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
       C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
       C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
       C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
       C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
       C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:654:in `block in converge'
       C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:649:in `catch'
       C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:649:in `converge'
       C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:688:in `converge_and_save'
       C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:269:in `run'
       C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:252:in `run_with_graceful_exit_option'
       C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:229:in `block in run_chef_client'
       C:/opscode/chef/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
       C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:212:in `run_chef_client'
       C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:402:in `block in interval_run_chef_client'
       C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `loop'
       C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `interval_run_chef_client'
       C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `run_application'
       C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
       C:/opscode/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
       C:/opscode/chef/bin/chef-client:67:in `load'
       C:/opscode/chef/bin/chef-client:67:in `<main>'
```

This is using chef 12.4.1 on windows 2012R2

### PR DESCRIPTION
**Pull request by mwrock**
This fixes #4024 and ignores the `gid` attribute on the windows platform. This also emits a warning if the gid is used on windows and suggests that the user use the `group` resource.

I had originally addressed this fix by implementing the gid/user association and adding the user to the group. However, I have switched to this approach for the following reasons:

1. The `gid` in linux refers to a user's "primary" group. Technicaly there is such a term in the windows API but it is conceptually different from linux and has no mapping to a specific local windows group.
2. Treating the gid as a local windows group is awkward because the gid/uid relationship in linux is 1 user to 1 group while windows users can be assigned to many local groups.
3. The implementation in windows is fairly verbose do to the need to pull in more win32 api bindings and adds complexity to the code.
4. The required functionality of maintaining local user/group relationships is present already in chef using the `group` resource.

### CODE REVIEW

**Comment by chefsalim** [comment]
LGTM :+1: 

As a side note, we should update the docs to reflect this as well.

File: lib/chef/provider/user/windows.rb [hunk 1]
```diff
@@ -35,6 +35,10 @@ def initialize(new_resource,run_context)
         end
 
         def load_current_resource
+          if @new_resource.gid
```
Comment (jaym) [inline lib/chef/provider/user/windows.rb]: there's a typo here
th -> to

**Comment by jaym** [comment]
In your commit message, could you write something about why this path was taken over adding the user to the group specified in gid. Other than that, :+1:

File: lib/chef/provider/user/windows.rb (hunk 1 above)
Comment (mwrock) [inline lib/chef/provider/user/windows.rb]: my fgod why am i not capable of typo free narrative

**Comment by mwrock** [comment]
good point @chefsalim about the docs. How is that done?
